#!/bin/bash

# MaiFarm Backup Cron Configuration
# Sets up automated backup schedules

set -euo pipefail

# Configuration
BACKUP_SCRIPT="/var/www/maifarm/scripts/db/backup-automation.sh"
CRON_USER="www-data"
LOG_DIR="/var/log/maifarm"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}MaiFarm Backup Cron Setup${NC}"
echo "========================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root (use sudo)${NC}"
    exit 1
fi

# Create log directory
mkdir -p "$LOG_DIR"
chown "$CRON_USER:$CRON_USER" "$LOG_DIR"

# Backup cron schedule configuration
cat << 'EOF' > /etc/cron.d/maifarm-backup
# MaiFarm Automated Backup Schedule
# Generated by backup-cron.sh

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Environment variables for backup
BACKUP_DIR=/var/backups/maifarm
DB_NAME=maifarm_prod
DB_USER=maifarm
# Add DB_PASSWORD, REDIS_PASSWORD, S3_BUCKET, SLACK_WEBHOOK_URL to /etc/environment

# Daily backup at 2:00 AM
0 2 * * * www-data /var/www/maifarm/scripts/db/backup-automation.sh >> /var/log/maifarm/backup.log 2>&1

# Weekly full backup on Sunday at 3:00 AM
0 3 * * 0 www-data /var/www/maifarm/scripts/db/backup-automation.sh full >> /var/log/maifarm/backup.log 2>&1

# Incremental backup every 6 hours (8AM, 2PM, 8PM)
0 8,14,20 * * * www-data /var/www/maifarm/scripts/db/backup-automation.sh incremental >> /var/log/maifarm/backup.log 2>&1

# Database-only backup every 4 hours
0 */4 * * * www-data /var/www/maifarm/scripts/db/backup-database-only.sh >> /var/log/maifarm/backup.log 2>&1

# Clean old backups every Monday at 4:00 AM
0 4 * * 1 www-data /var/www/maifarm/scripts/db/backup-cleanup.sh >> /var/log/maifarm/backup.log 2>&1

# Verify backup integrity daily at 5:00 AM
0 5 * * * www-data /var/www/maifarm/scripts/db/backup-verify.sh >> /var/log/maifarm/backup.log 2>&1
EOF

# Create database-only backup script
cat << 'EOF' > /var/www/maifarm/scripts/db/backup-database-only.sh
#!/bin/bash
# Quick database-only backup

source /etc/environment

BACKUP_DIR="${BACKUP_DIR:-/var/backups/maifarm}/db-only"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
mkdir -p "$BACKUP_DIR"

# Backup database
export PGPASSWORD="$DB_PASSWORD"
pg_dump -h localhost -U "$DB_USER" -d "$DB_NAME" | gzip -9 > "$BACKUP_DIR/db_${TIMESTAMP}.sql.gz"
unset PGPASSWORD

# Keep only last 24 hours of database-only backups
find "$BACKUP_DIR" -name "db_*.sql.gz" -mtime +1 -delete

echo "[$(date)] Database backup completed: db_${TIMESTAMP}.sql.gz"
EOF

# Create backup cleanup script
cat << 'EOF' > /var/www/maifarm/scripts/db/backup-cleanup.sh
#!/bin/bash
# Cleanup old backups based on retention policy

source /etc/environment

BACKUP_BASE="${BACKUP_DIR:-/var/backups/maifarm}"

# Retention policy
DAILY_RETENTION=7
WEEKLY_RETENTION=28
MONTHLY_RETENTION=365
DB_ONLY_RETENTION=1

echo "[$(date)] Starting backup cleanup..."

# Clean daily backups
find "$BACKUP_BASE/daily" -type f -mtime +$DAILY_RETENTION -delete 2>/dev/null || true

# Clean weekly backups
find "$BACKUP_BASE/weekly" -type f -mtime +$WEEKLY_RETENTION -delete 2>/dev/null || true

# Clean monthly backups
find "$BACKUP_BASE/monthly" -type f -mtime +$MONTHLY_RETENTION -delete 2>/dev/null || true

# Clean database-only backups
find "$BACKUP_BASE/db-only" -type f -mtime +$DB_ONLY_RETENTION -delete 2>/dev/null || true

# Clean old timestamped directories
find "$BACKUP_BASE" -maxdepth 1 -type d -name "[0-9]*" -mtime +30 -exec rm -rf {} \; 2>/dev/null || true

# Report disk usage
DISK_USAGE=$(du -sh "$BACKUP_BASE" | cut -f1)
echo "[$(date)] Cleanup completed. Backup directory size: $DISK_USAGE"
EOF

# Create backup verification script
cat << 'EOF' > /var/www/maifarm/scripts/db/backup-verify.sh
#!/bin/bash
# Verify backup integrity

source /etc/environment

BACKUP_BASE="${BACKUP_DIR:-/var/backups/maifarm}"
LATEST="$BACKUP_BASE/latest"

if [ ! -L "$LATEST" ]; then
    echo "[$(date)] ERROR: No latest backup found"
    exit 1
fi

echo "[$(date)] Verifying latest backup..."

# Check backup components
ERRORS=0

# Check database backup
if ! find "$LATEST/database" -name "*.sql.gz" -type f | grep -q .; then
    echo "[$(date)] ERROR: Database backup missing"
    ((ERRORS++))
fi

# Check file sizes
for file in "$LATEST"/**/*.gz; do
    if [ -f "$file" ]; then
        SIZE=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
        if [ "$SIZE" -eq 0 ]; then
            echo "[$(date)] ERROR: Empty backup file: $file"
            ((ERRORS++))
        fi
    fi
done

# Verify checksums
if find "$LATEST" -name "*.sha256" -print -quit | grep -q .; then
    cd "$LATEST"
    for checksum in $(find . -name "*.sha256"); do
        file="${checksum%.sha256}"
        if [ -f "$file" ]; then
            if ! sha256sum -c "$checksum" > /dev/null 2>&1; then
                echo "[$(date)] ERROR: Checksum mismatch: $file"
                ((ERRORS++))
            fi
        fi
    done
    cd - > /dev/null
fi

if [ $ERRORS -eq 0 ]; then
    echo "[$(date)] Backup verification passed"
else
    echo "[$(date)] Backup verification failed with $ERRORS errors"

    # Send alert if webhook configured
    if [ -n "$SLACK_WEBHOOK_URL" ]; then
        curl -X POST "$SLACK_WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d "{\"text\": \"⚠️ MaiFarm backup verification failed with $ERRORS errors\"}" 2>/dev/null || true
    fi
    exit 1
fi
EOF

# Make scripts executable
chmod +x /var/www/maifarm/scripts/db/backup-*.sh
chown "$CRON_USER:$CRON_USER" /var/www/maifarm/scripts/db/backup-*.sh

# Create logrotate configuration
cat << 'EOF' > /etc/logrotate.d/maifarm-backup
/var/log/maifarm/backup.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 640 www-data www-data
    sharedscripts
    postrotate
        # Send summary to monitoring
        tail -n 100 /var/log/maifarm/backup.log.1 | grep -E "(ERROR|WARNING|completed)" > /tmp/backup-summary.txt
        # Add notification logic here if needed
    endscript
}
EOF

# Create systemd timer as alternative to cron
cat << 'EOF' > /etc/systemd/system/maifarm-backup.service
[Unit]
Description=MaiFarm Backup Service
After=postgresql.service redis.service

[Service]
Type=oneshot
User=www-data
Group=www-data
ExecStart=/var/www/maifarm/scripts/db/backup-automation.sh
StandardOutput=append:/var/log/maifarm/backup.log
StandardError=append:/var/log/maifarm/backup.log

[Install]
WantedBy=multi-user.target
EOF

cat << 'EOF' > /etc/systemd/system/maifarm-backup.timer
[Unit]
Description=MaiFarm Daily Backup Timer
Requires=maifarm-backup.service

[Timer]
OnCalendar=daily
OnCalendar=02:00
Persistent=true

[Install]
WantedBy=timers.target
EOF

# Reload systemd
systemctl daemon-reload

# Enable backup timer
systemctl enable maifarm-backup.timer

echo ""
echo -e "${GREEN}Backup automation setup completed!${NC}"
echo ""
echo "Configured schedules:"
echo "- Daily backup: 2:00 AM"
echo "- Weekly full backup: Sunday 3:00 AM"
echo "- Incremental backup: Every 6 hours"
echo "- Database-only backup: Every 4 hours"
echo "- Cleanup: Monday 4:00 AM"
echo "- Verification: Daily 5:00 AM"
echo ""
echo -e "${YELLOW}Important:${NC}"
echo "1. Add sensitive environment variables to /etc/environment:"
echo "   - DB_PASSWORD=your_password"
echo "   - REDIS_PASSWORD=your_password"
echo "   - S3_BUCKET=your_bucket (optional)"
echo "   - SLACK_WEBHOOK_URL=your_webhook (optional)"
echo ""
echo "2. Test backup script manually:"
echo "   sudo -u www-data /var/www/maifarm/scripts/db/backup-automation.sh"
echo ""
echo "3. Monitor backup logs:"
echo "   tail -f /var/log/maifarm/backup.log"
echo ""
echo "4. Start systemd timer (alternative to cron):"
echo "   systemctl start maifarm-backup.timer"
echo ""