/**
 * Causal Model Types - DEMOCRITUS-Inspired Implementation
 *
 * Based on "Large Causal Models from Large Language Models" (arxiv 2512.07796)
 * by Sridhar Mahadevan
 *
 * DEMOCRITUS: A system for extracting, organizing, and visualizing
 * large causal models (LCMs) from LLM queries.
 *
 * Six-module pipeline:
 * 1. Extract - Parse prompt for causal statements
 * 2. Organize - Group triples by relationship type
 * 3. Detect - Find conflicting claims
 * 4. Resolve - Apply resolution strategy
 * 5. Build - Construct directed graph
 * 6. Order - Topological sort for task sequence
 */

/**
 * Causal relationship types between entities/actions
 */
export type CausalRelationship =
  | 'causes'      // A directly causes B
  | 'enables'     // A makes B possible
  | 'prevents'    // A blocks B from occurring
  | 'requires'    // A needs B to exist/complete first
  | 'follows'     // A comes after B (temporal)
  | 'produces'    // A creates/outputs B
  | 'consumes'    // A uses up B
  | 'modifies'    // A changes B
  | 'triggers';   // A initiates B

/**
 * Source of a causal claim
 */
export type CausalSource =
  | 'extracted'    // Parsed from prompt
  | 'inferred'     // Derived from other triples
  | 'user_defined' // Explicitly specified by user
  | 'system';      // Generated by the system

/**
 * A causal triple: cause → relationship → effect
 */
export interface CausalTriple {
  /** Unique identifier */
  id: string;
  /** The causing entity/action */
  cause: string;
  /** The affected entity/action */
  effect: string;
  /** Type of causal relationship */
  relationship: CausalRelationship;
  /** Confidence score (0-1) */
  confidence: number;
  /** How this triple was obtained */
  source: CausalSource;
  /** Supporting evidence or reasoning */
  evidence?: string[];
  /** IDs of conflicting triples */
  conflictsWith?: string[];
  /** Whether this triple is active (not overridden by resolution) */
  active: boolean;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Conflict types between causal claims
 */
export type ConflictType =
  | 'contradiction'  // A causes B AND A prevents B
  | 'inconsistency'  // A enables B AND A prevents B
  | 'ambiguity'      // Multiple incompatible relationship claims
  | 'cycle';         // Circular dependency detected

/**
 * Resolution strategies for conflicts
 */
export type ResolutionStrategy =
  | 'confidence'  // Select triple with highest confidence
  | 'evidence'    // Select triple with most evidence
  | 'recency'     // Prefer more recently extracted claims
  | 'authority'   // Prefer user-defined over inferred
  | 'majority'    // If multiple support one side
  | 'manual';     // Flag for human review

/**
 * Conflict resolution result
 */
export interface ConflictResolution {
  /** Strategy used to resolve */
  strategy: ResolutionStrategy;
  /** ID of the triple that won */
  resolvedTripleId: string;
  /** Reason for resolution */
  reason: string;
  /** Timestamp of resolution */
  resolvedAt: Date;
  /** Who/what resolved it */
  resolvedBy?: string;
}

/**
 * A conflict between causal claims
 */
export interface CausalConflict {
  /** Unique identifier */
  id: string;
  /** IDs of conflicting triples */
  tripleIds: string[];
  /** Type of conflict */
  type: ConflictType;
  /** Description of the conflict */
  description: string;
  /** Resolution (if resolved) */
  resolution?: ConflictResolution;
  /** Whether this conflict is resolved */
  resolved: boolean;
  /** Detection timestamp */
  detectedAt: Date;
}

/**
 * Node types in the causal graph
 */
export type CausalNodeType =
  | 'action'      // An operation to perform
  | 'state'       // A condition or state
  | 'goal'        // A target to achieve
  | 'entity'      // An object in the domain
  | 'constraint'  // A limitation or rule
  | 'milestone';  // A checkpoint in the process

/**
 * A node in the causal graph
 */
export interface CausalNode {
  /** Unique identifier (matches entity/action ID) */
  id: string;
  /** Display label */
  label: string;
  /** Node type */
  type: CausalNodeType;
  /** Number of incoming edges */
  inDegree: number;
  /** Number of outgoing edges */
  outDegree: number;
  /** Whether this is a root node (no incoming) */
  isRoot: boolean;
  /** Whether this is a leaf node (no outgoing) */
  isLeaf: boolean;
  /** Position in topological order (-1 if in cycle) */
  topologicalIndex?: number;
  /** Additional properties */
  properties?: Record<string, unknown>;
}

/**
 * An edge in the causal graph
 */
export interface CausalEdge {
  /** Unique identifier */
  id: string;
  /** Source node ID */
  source: string;
  /** Target node ID */
  target: string;
  /** Edge weight (based on confidence) */
  weight: number;
  /** Relationship type */
  relationship: CausalRelationship;
  /** Original triple ID this edge represents */
  tripleId: string;
  /** Whether this edge is on the critical path */
  critical?: boolean;
}

/**
 * The complete causal graph structure
 */
export interface CausalGraph {
  /** All nodes in the graph */
  nodes: CausalNode[];
  /** All edges in the graph */
  edges: CausalEdge[];
  /** Topological order of node IDs (for task sequencing) */
  topologicalOrder: string[];
  /** Whether the graph is a DAG (no cycles) */
  isDAG: boolean;
  /** Detected cycles (if any) */
  cycles?: string[][];
  /** Critical path through the graph */
  criticalPath?: string[];
  /** Graph statistics */
  stats: CausalGraphStats;
}

/**
 * Statistics about the causal graph
 */
export interface CausalGraphStats {
  /** Total number of nodes */
  nodeCount: number;
  /** Total number of edges */
  edgeCount: number;
  /** Number of root nodes */
  rootCount: number;
  /** Number of leaf nodes */
  leafCount: number;
  /** Maximum depth of the graph */
  maxDepth: number;
  /** Average confidence of edges */
  avgConfidence: number;
  /** Number of connected components */
  componentCount: number;
}

/**
 * Conflict resolution status
 */
export type ConflictResolutionStatus =
  | 'pending'        // No conflicts detected yet
  | 'in_progress'    // Conflicts being resolved
  | 'resolved'       // All conflicts resolved
  | 'manual_review'; // Some conflicts need human review

/**
 * The complete Causal Model
 *
 * Represents causal relationships extracted from the farm prompt,
 * used for intelligent task ordering and dependency management.
 */
export interface CausalModel {
  /** Unique identifier */
  id: string;
  /** Associated farm ID */
  farmId: string;
  /** Associated problem model ID (if any) */
  problemModelId?: string;
  /** Model version */
  version: number;

  /** Extracted causal triples */
  triples: CausalTriple[];
  /** Constructed causal graph */
  graph: CausalGraph;
  /** Detected conflicts */
  conflicts: CausalConflict[];
  /** Conflict resolution status */
  conflictResolutionStatus: ConflictResolutionStatus;

  /** Task execution order derived from topological sort */
  topologicalOrder: string[];

  /** Original prompt used for extraction */
  sourcePrompt?: string;
  /** AI provider used for extraction */
  extractedBy?: 'claude' | 'openai' | 'ollama';
  /** Extraction timestamp */
  extractedAt?: Date;

  /** Additional metadata */
  metadata: Record<string, unknown>;

  /** Creation timestamp */
  createdAt: Date;
  /** Last update timestamp */
  updatedAt: Date;
}

/**
 * Request to extract causal model from a prompt
 */
export interface CausalModelExtractionRequest {
  /** Farm ID */
  farmId: string;
  /** Farm prompt to analyze */
  prompt: string;
  /** Associated problem model (for context) */
  problemModel?: {
    entities: Array<{ id: string; name: string; type: string }>;
    actions: Array<{ id: string; name: string; description: string }>;
  };
  /** AI provider to use */
  provider?: 'claude' | 'openai' | 'ollama';
  /** Additional context */
  context?: string;
}

/**
 * Result of the extraction pipeline
 */
export interface CausalExtractionResult {
  /** Extracted triples */
  triples: CausalTriple[];
  /** Extraction confidence */
  confidence: number;
  /** Extraction duration in ms */
  durationMs: number;
  /** Any warnings during extraction */
  warnings?: string[];
}

/**
 * Result of conflict detection
 */
export interface ConflictDetectionResult {
  /** Detected conflicts */
  conflicts: CausalConflict[];
  /** Whether any critical conflicts exist */
  hasCriticalConflicts: boolean;
  /** Detection duration in ms */
  durationMs: number;
}

/**
 * Result of graph construction
 */
export interface GraphConstructionResult {
  /** Constructed graph */
  graph: CausalGraph;
  /** Construction duration in ms */
  durationMs: number;
  /** Any issues during construction */
  issues?: string[];
}

/**
 * Summary of a causal model for display
 */
export interface CausalModelSummary {
  id: string;
  farmId: string;
  tripleCount: number;
  nodeCount: number;
  edgeCount: number;
  conflictCount: number;
  unresolvedConflicts: number;
  isDAG: boolean;
  conflictResolutionStatus: ConflictResolutionStatus;
  createdAt: Date;
}

/**
 * Agent's view of the causal model
 * Serialized to JSON for injection into agent prompts
 */
export interface AgentCausalModelContext {
  /** Task ordering from topological sort */
  taskOrder: string[];
  /** Dependencies for this agent's tasks */
  dependencies: Array<{
    task: string;
    dependsOn: string[];
    relationship: CausalRelationship;
  }>;
  /** Constraints from causal analysis */
  causalConstraints: Array<{
    description: string;
    type: ConflictType | CausalRelationship;
  }>;
  /** Critical path tasks (if on critical path) */
  criticalPathTasks?: string[];
}

/**
 * Pipeline stage results for debugging/monitoring
 */
export interface CausalPipelineResults {
  /** Stage 1: Extraction */
  extraction: CausalExtractionResult;
  /** Stage 2: Organization (triples grouped by relationship) */
  organization: Record<CausalRelationship, CausalTriple[]>;
  /** Stage 3: Conflict detection */
  detection: ConflictDetectionResult;
  /** Stage 4: Resolution (resolved conflicts) */
  resolution: CausalConflict[];
  /** Stage 5: Graph construction */
  construction: GraphConstructionResult;
  /** Stage 6: Topological ordering */
  ordering: {
    order: string[];
    isDAG: boolean;
    cycles: string[][];
    durationMs: number;
  };
  /** Total pipeline duration */
  totalDurationMs: number;
}

/**
 * Event emitted during causal model processing
 */
export interface CausalModelEvent {
  type: 'extraction_started' | 'extraction_completed' |
        'conflict_detected' | 'conflict_resolved' |
        'graph_constructed' | 'ordering_completed' |
        'pipeline_completed' | 'error';
  farmId: string;
  modelId?: string;
  data?: Record<string, unknown>;
  timestamp: Date;
}
