#!/usr/bin/env python3
"""
GPT-OSS Agent for MaiFarm

This agent connects to the local GPT-OSS server and executes prompts.
It integrates with the MaiFarm orchestration system.
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("[GPT-OSS] ERROR: requests library not installed. Run: pip install requests")
    sys.exit(1)


def log(message: str, level: str = "INFO") -> None:
    """Log a message with timestamp."""
    timestamp = datetime.now().strftime("%H:%M:%S")
    output = f"[{timestamp}] [{level}] {message}"
    print(output, flush=True)


def read_prompt_file(path: str) -> str:
    """Read prompt from file."""
    with open(path, 'r', encoding='utf-8') as f:
        return f.read().strip()


def normalize_host(host: str) -> str:
    """Normalize host URL by removing trailing /v1 or /v1/ if present."""
    host = host.rstrip('/')
    if host.endswith('/v1'):
        host = host[:-3]
    return host


def check_server_health(host: str, timeout: int = 5) -> dict:
    """Check GPT-OSS server health."""
    # Normalize host to remove /v1 suffix if present
    base_host = normalize_host(host)
    try:
        response = requests.get(f"{base_host}/health", timeout=timeout)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        return {"error": str(e), "healthy": False}


def call_gpt_oss_api(
    host: str,
    prompt: str,
    agent_name: str,
    model: str = "openai/gpt-oss-20b",
    max_tokens: int = 4096,
    temperature: float = 0.6,
    timeout: int = 120
) -> dict:
    """Call the GPT-OSS API."""
    # Normalize host to remove /v1 suffix if present (we add it ourselves)
    base_host = normalize_host(host)
    try:
        response = requests.post(
            f"{base_host}/v1/chat/completions",
            json={
                "model": model,
                "messages": [
                    {
                        "role": "system",
                        "content": f"You are {agent_name}, an AI agent working in the MaiFarm multi-agent system. "
                                   "You collaborate with other agents to complete tasks efficiently."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "temperature": temperature,
                "max_tokens": max_tokens,
                "stream": False
            },
            timeout=timeout
        )
        response.raise_for_status()
        return response.json()
    except requests.exceptions.Timeout:
        return {"error": "Request timed out", "success": False}
    except requests.exceptions.RequestException as e:
        return {"error": str(e), "success": False}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON response", "success": False}


def extract_code_blocks(content: str) -> list:
    """Extract code blocks from markdown-style content."""
    import re
    pattern = r'```[\w]*\n([\s\S]*?)\n```'
    matches = re.findall(pattern, content)
    return matches


def generate_mini_response(prompt: str, agent_name: str) -> str:
    """Generate a deterministic mini backend response when external server is unavailable."""
    import hashlib
    import re

    # Extract key verbs/actions from prompt
    verbs = ['create', 'build', 'review', 'summarize', 'optimize', 'list', 'document', 'analyze', 'explore', 'test', 'fix']
    sentences = [s.strip() for s in re.split(r'[.\n]', prompt) if s.strip()]

    actions = []
    for sentence in sentences[:5]:
        lower = sentence.lower()
        for verb in verbs:
            if verb in lower:
                actions.append(sentence[:100])
                break

    if not actions and sentences:
        actions.append(f"Process request: {sentences[0][:80]}")

    # Use hash for deterministic variation
    seed = hashlib.sha1(prompt.encode()).hexdigest()
    variation = int(seed[:4], 16) % 3

    summary = prompt[:200].replace('`', '').replace('\n', ' ').strip()
    if len(prompt) > 200:
        summary += "..."

    if variation == 0:
        response = f"""### Summary
- {summary}

### Key Actions
{chr(10).join(f'{i+1}. {a}' for i, a in enumerate(actions)) if actions else '1. Clarify requirements and plan approach.'}

### Considerations
- Validate filesystem access before performing mutations.
- Capture telemetry for any long-running subprocess.

### Assigned To
- Agent {agent_name}

### Generated By
- MaiFarm GPT-OSS mini backend (offline mode)"""
    elif variation == 1:
        response = f"""### Proposed Workflow
- Initiate discovery pass to collect context.
- Break work into atomic tasks for coordination.
- Emit intermediate progress updates.

### Immediate TODOs
{chr(10).join(f'- {a}' for a in actions) if actions else '- Clarify acceptance criteria.'}

### Status
- Running in offline mode with mini backend.
- Agent {agent_name} processing request.

### Generated By
- MaiFarm GPT-OSS mini backend (offline mode)"""
    else:
        response = f"""### Task Acknowledgment
- Request received and queued for processing.
- Agent {agent_name} will execute with available resources.

### Request Summary
- Prompt length: {len(prompt)} characters
- Actions identified: {len(actions)}

### Next Steps
1. Analyze request requirements.
2. Execute primary objective with available tools.
3. Report results to harvest stream.

### Generated By
- MaiFarm GPT-OSS mini backend (offline mode)"""

    return response


def execute_agent(
    prompt: str,
    agent_name: str,
    host: str = "http://localhost:8000",
    workspace_dir: Optional[str] = None
) -> None:
    """Execute the GPT-OSS agent with the given prompt."""

    log(f"[GPT-OSS] Agent {agent_name} starting...")
    log(f"[GPT-OSS] Connecting to {host}")

    # Check server health
    use_mini_backend = False
    health = check_server_health(host)
    if health.get("error"):
        log(f"[GPT-OSS] Server health check failed: {health['error']}", "ERROR")
        log("[GPT-OSS] Will use mini backend fallback for deterministic responses...")
        use_mini_backend = True
    else:
        log(f"[GPT-OSS] Server healthy: {health.get('backend', 'unknown')} backend")
        log(f"[GPT-OSS] Model: {health.get('model', 'unknown')}")

    # Log prompt summary
    prompt_preview = prompt[:200] + "..." if len(prompt) > 200 else prompt
    log(f"[GPT-OSS] Received prompt: {prompt_preview}")

    result = None
    start_time = time.time()

    if use_mini_backend:
        # Use the embedded mini backend for deterministic responses
        log("[GPT-OSS] Generating response with mini backend...")
        result = generate_mini_response(prompt, agent_name)
        elapsed = time.time() - start_time
        log(f"[GPT-OSS] Mini backend response generated in {elapsed:.2f}s")
    else:
        # Call GPT-OSS API
        log("[GPT-OSS] Sending request to GPT-OSS API...")

        response = call_gpt_oss_api(
            host=host,
            prompt=prompt,
            agent_name=agent_name,
            max_tokens=4096,
            temperature=0.6
        )

        elapsed = time.time() - start_time
        log(f"[GPT-OSS] Response received in {elapsed:.2f}s")

        # Handle error - fall back to mini backend
        if response.get("error"):
            log(f"[GPT-OSS] API Error: {response['error']}", "ERROR")
            log("[GPT-OSS] Falling back to mini backend...")
            result = generate_mini_response(prompt, agent_name)
        else:
            # Extract response from API
            try:
                result = response.get("choices", [{}])[0].get("message", {}).get("content", "")
            except Exception as e:
                log(f"[GPT-OSS] Error extracting response: {e}", "ERROR")
                result = generate_mini_response(prompt, agent_name)

    # Display result
    if result:
        log("[GPT-OSS] === Response Start ===")
        print(result, flush=True)
        log("[GPT-OSS] === Response End ===")

        # Extract code blocks and save if workspace is available
        code_blocks = extract_code_blocks(result)
        if code_blocks and workspace_dir:
            workspace = Path(workspace_dir)
            for i, code in enumerate(code_blocks):
                filename = workspace / f"gpt_oss_output_{i}.txt"
                try:
                    filename.write_text(code, encoding='utf-8')
                    log(f"[GPT-OSS] Created file: {filename}")
                except Exception as e:
                    log(f"[GPT-OSS] Failed to write file: {e}", "WARN")

        log("[GPT-OSS] Task completed successfully")
    else:
        log("[GPT-OSS] Empty response received", "WARN")

    # Keep agent running for monitoring
    log("[GPT-OSS] Agent entering idle monitoring mode...")
    idle_count = 0
    while True:
        time.sleep(30)
        idle_count += 1
        if idle_count % 2 == 0:  # Log every minute
            log(f"[GPT-OSS] Agent idle ({idle_count * 30}s elapsed)")


def main():
    parser = argparse.ArgumentParser(description="GPT-OSS Agent for MaiFarm")
    parser.add_argument("--prompt", help="Inline prompt text")
    parser.add_argument("--prompt-file", type=Path, help="Path to prompt file")
    parser.add_argument("--host", default=os.environ.get("GPT_OSS_HOST", "http://localhost:8000"),
                        help="GPT-OSS server host")
    parser.add_argument("--agent-name", default=os.environ.get("AGENT_NAME", "GPT-OSS Agent"),
                        help="Agent name")
    parser.add_argument("--workspace", default=os.environ.get("WORKSPACE_DIR"),
                        help="Workspace directory for output files")

    args = parser.parse_args()

    # Get prompt
    prompt = None
    if args.prompt:
        prompt = args.prompt
    elif args.prompt_file:
        if args.prompt_file.exists():
            prompt = read_prompt_file(str(args.prompt_file))
        else:
            log(f"[GPT-OSS] Prompt file not found: {args.prompt_file}", "ERROR")
            sys.exit(1)
    elif os.environ.get("AGENT_PROMPT"):
        prompt = os.environ["AGENT_PROMPT"]
    else:
        log("[GPT-OSS] No prompt provided. Use --prompt, --prompt-file, or AGENT_PROMPT env var", "ERROR")
        sys.exit(1)

    # Execute agent
    try:
        execute_agent(
            prompt=prompt,
            agent_name=args.agent_name,
            host=args.host,
            workspace_dir=args.workspace
        )
    except KeyboardInterrupt:
        log("[GPT-OSS] Agent interrupted by user")
        sys.exit(0)
    except Exception as e:
        log(f"[GPT-OSS] Agent error: {e}", "ERROR")
        sys.exit(1)


if __name__ == "__main__":
    main()
