-- Migration: Assistant System Tables
-- Description: Tables for the Assistant agent that runs parallel to Orchestrator

-- Nudges table - stores nudge history
CREATE TABLE IF NOT EXISTS assistant_nudges (
    nudge_id VARCHAR(36) PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    episode_id VARCHAR(36),
    message TEXT NOT NULL,
    reason TEXT,
    attempt_number INTEGER DEFAULT 1,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acknowledged BOOLEAN DEFAULT FALSE,
    ack_response TEXT,
    ack_timestamp TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for session lookups
CREATE INDEX IF NOT EXISTS idx_assistant_nudges_session ON assistant_nudges(session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_nudges_timestamp ON assistant_nudges(timestamp DESC);

-- Summaries table - stores session summaries
CREATE TABLE IF NOT EXISTS assistant_summaries (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    summary TEXT NOT NULL,
    goals JSONB,
    artifacts JSONB,
    issues JSONB,
    version INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for session lookups
CREATE INDEX IF NOT EXISTS idx_assistant_summaries_session ON assistant_summaries(session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_summaries_created ON assistant_summaries(created_at DESC);

-- Contexts table - stores context snapshots
CREATE TABLE IF NOT EXISTS assistant_contexts (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    context JSONB NOT NULL,
    status VARCHAR(50),
    progress DECIMAL(5,4),
    active_agents INTEGER DEFAULT 0,
    total_agents INTEGER DEFAULT 0,
    tokens_used INTEGER DEFAULT 0,
    estimated_cost DECIMAL(10,6) DEFAULT 0,
    tasks_completed INTEGER DEFAULT 0,
    files_generated INTEGER DEFAULT 0,
    error_count INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for session lookups
CREATE INDEX IF NOT EXISTS idx_assistant_contexts_session ON assistant_contexts(session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_contexts_updated ON assistant_contexts(updated_at DESC);

-- Events table - stores session events for replay/analysis
CREATE TABLE IF NOT EXISTS assistant_events (
    id SERIAL PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    session_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    agent_id VARCHAR(36),
    agent_name VARCHAR(255),
    correlation_id VARCHAR(36),
    data JSONB,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for event lookups
CREATE INDEX IF NOT EXISTS idx_assistant_events_session ON assistant_events(session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_events_type ON assistant_events(event_type);
CREATE INDEX IF NOT EXISTS idx_assistant_events_timestamp ON assistant_events(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_assistant_events_agent ON assistant_events(agent_id) WHERE agent_id IS NOT NULL;

-- Stall detection history
CREATE TABLE IF NOT EXISTS assistant_stall_history (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    stall_detected_at TIMESTAMPTZ NOT NULL,
    inactivity_duration_seconds INTEGER,
    reason TEXT,
    signals_checked JSONB,
    nudge_sent BOOLEAN DEFAULT FALSE,
    nudge_id VARCHAR(36),
    resolved_at TIMESTAMPTZ,
    resolution VARCHAR(50)
);

-- Index for stall history
CREATE INDEX IF NOT EXISTS idx_assistant_stall_session ON assistant_stall_history(session_id);
CREATE INDEX IF NOT EXISTS idx_assistant_stall_detected ON assistant_stall_history(stall_detected_at DESC);

-- Function to clean up old assistant data
CREATE OR REPLACE FUNCTION cleanup_old_assistant_data(days_to_keep INTEGER DEFAULT 30)
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER := 0;
    cutoff_date TIMESTAMPTZ;
BEGIN
    cutoff_date := NOW() - (days_to_keep || ' days')::INTERVAL;

    DELETE FROM assistant_events WHERE timestamp < cutoff_date;
    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    DELETE FROM assistant_summaries WHERE created_at < cutoff_date;
    DELETE FROM assistant_contexts WHERE updated_at < cutoff_date;
    DELETE FROM assistant_nudges WHERE timestamp < cutoff_date;
    DELETE FROM assistant_stall_history WHERE stall_detected_at < cutoff_date;

    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Add comment
COMMENT ON TABLE assistant_nudges IS 'Stores nudge messages sent by Assistant to Orchestrator';
COMMENT ON TABLE assistant_summaries IS 'Stores markdown summaries generated by Assistant';
COMMENT ON TABLE assistant_contexts IS 'Stores context snapshots for session state tracking';
COMMENT ON TABLE assistant_events IS 'Stores all session events for replay and analysis';
COMMENT ON TABLE assistant_stall_history IS 'Stores history of stall detections for debugging';
