import React from 'react';
import { motion } from 'framer-motion';
import { ConceptQuadExplainer } from '../Dashboard/ConceptQuadExplainer';
import { BookOpenIcon, InformationCircleIcon, QuestionMarkCircleIcon } from '@heroicons/react/24/outline';

const InfoSettings: React.FC = () => {
  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <div className="flex items-center space-x-2 mb-2">
          <BookOpenIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
            Information & Documentation
          </h2>
        </div>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Learn about MaiFarm concepts and how to use the platform effectively
        </p>
      </div>

      {/* MaiFarm Concepts Section */}
      <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
        <div className="mb-4">
          <h3 className="text-base font-medium text-gray-900 dark:text-white mb-1">
            MaiFarm Core Concepts
          </h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Understand the key components of the MaiFarm ecosystem
          </p>
        </div>

        {/* Concept Explainer Component */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
        >
          <ConceptQuadExplainer />
        </motion.div>
      </div>

      {/* Quick Links Section */}
      <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
        <h3 className="text-base font-medium text-gray-900 dark:text-white mb-4">
          Quick Links & Resources
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <motion.a
            href="#getting-started"
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            className="flex items-start space-x-3 p-4 bg-gray-50 dark:bg-gray-900 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            <InformationCircleIcon className="w-5 h-5 text-blue-500 mt-0.5" />
            <div>
              <h4 className="text-sm font-medium text-gray-900 dark:text-white">
                Getting Started Guide
              </h4>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Learn the basics of creating and managing farms
              </p>
            </div>
          </motion.a>

          <motion.a
            href="#faq"
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            className="flex items-start space-x-3 p-4 bg-gray-50 dark:bg-gray-900 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            <QuestionMarkCircleIcon className="w-5 h-5 text-purple-500 mt-0.5" />
            <div>
              <h4 className="text-sm font-medium text-gray-900 dark:text-white">
                Frequently Asked Questions
              </h4>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Find answers to common questions
              </p>
            </div>
          </motion.a>
        </div>
      </div>

      {/* Glossary Section */}
      <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
        <h3 className="text-base font-medium text-gray-900 dark:text-white mb-4">
          Glossary of Terms
        </h3>
        <div className="space-y-3">
          <div className="p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
            <dt className="text-sm font-medium text-gray-900 dark:text-white">Farm</dt>
            <dd className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              An AI-powered development environment where multiple agents collaborate on tasks
            </dd>
          </div>
          <div className="p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
            <dt className="text-sm font-medium text-gray-900 dark:text-white">Agent</dt>
            <dd className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              An AI worker that performs specific tasks within a farm environment
            </dd>
          </div>
          <div className="p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
            <dt className="text-sm font-medium text-gray-900 dark:text-white">Harvest</dt>
            <dd className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              The collection of outputs and results generated by agents in a farm
            </dd>
          </div>
          <div className="p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
            <dt className="text-sm font-medium text-gray-900 dark:text-white">Barn</dt>
            <dd className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              A storage area for saved harvests, templates, and reusable resources
            </dd>
          </div>
          <div className="p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
            <dt className="text-sm font-medium text-gray-900 dark:text-white">Seeds</dt>
            <dd className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              Pre-configured templates and starting points for new farms
            </dd>
          </div>
        </div>
      </div>

      {/* Version Information */}
      <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
        <h3 className="text-base font-medium text-gray-900 dark:text-white mb-2">
          Version Information
        </h3>
        <div className="text-sm text-gray-500 dark:text-gray-400">
          <p>MaiFarm Version: 2.5.0</p>
          <p>Last Updated: January 2025</p>
        </div>
      </div>
    </div>
  );
};

export default InfoSettings;