import PDFDocument from 'pdfkit';
import sharp from 'sharp';
import { optimize } from 'svgo';
import { IExportService, ExportOptions, ExportResult } from './types.js';
import { cacheService } from './cacheService.js';

export class ExportService implements IExportService {
  async exportInfographic(data: any, options: ExportOptions): Promise<ExportResult> {
    const cacheKey = `export:${JSON.stringify({ data: data.id, options })}`;
    const cached = await cacheService.get<ExportResult>(cacheKey);
    
    if (cached) {
      return cached;
    }

    let result: ExportResult;

    switch (options.format) {
      case 'png':
        result = await this.exportAsPNG(data, options);
        break;
      case 'pdf':
        result = await this.exportAsPDF(data, options);
        break;
      case 'svg':
        result = await this.exportAsSVG(data, options);
        break;
      default:
        throw new Error(`Unsupported export format: ${options.format}`);
    }

    await cacheService.set(cacheKey, result, { ttl: 3600 });
    
    return result;
  }

  private async exportAsPNG(data: any, options: ExportOptions): Promise<ExportResult> {
    const { width = 1920, height = 1080, quality = 90, dpi = 300 } = options;
    
    let pngBuffer: Buffer;
    
    if (data.svg) {
      pngBuffer = await this.convertSVGToPNG(data.svg, options);
    } else if (data.html) {
      // For HTML content, we'd need a headless browser
      // For now, create a placeholder image
      pngBuffer = await this.createPlaceholderPNG(width, height, data.title || 'Infographic');
    } else {
      throw new Error('No valid input data for PNG export');
    }

    const optimizedBuffer = await this.optimizeOutput(pngBuffer, 'png');

    return {
      format: 'png',
      data: optimizedBuffer,
      size: { width, height },
      fileSize: optimizedBuffer.length,
      metadata: {
        dpi,
        quality,
        createdAt: new Date(),
        ...options.metadata
      }
    };
  }

  private async exportAsPDF(data: any, options: ExportOptions): Promise<ExportResult> {
    const { width = 612, height = 792 } = options; // Letter size in points
    
    const doc = new PDFDocument({
      size: [width, height],
      info: {
        Title: options.metadata?.title || 'Trump News Infographic',
        Author: options.metadata?.author || 'MaiFarm System',
        Subject: options.metadata?.subject || 'News Analysis',
        Keywords: options.metadata?.keywords?.join(', ') || '',
        CreationDate: new Date()
      }
    });

    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));

    // Add header
    doc.fontSize(24)
       .text(data.title || 'Trump News Analysis', 50, 50, { align: 'center' });

    // Add timestamp
    doc.fontSize(12)
       .text(`Generated: ${new Date().toLocaleString()}`, 50, 100, { align: 'center' });

    // Add main content sections
    if (data.sections) {
      let yPosition = 150;
      
      data.sections.forEach((section: any) => {
        if (yPosition > height - 100) {
          doc.addPage();
          yPosition = 50;
        }

        // Section title
        doc.fontSize(18)
           .text(section.title, 50, yPosition);
        yPosition += 30;

        // Section content
        if (section.content) {
          doc.fontSize(12)
             .text(section.content, 50, yPosition, {
               width: width - 100,
               align: 'left'
             });
          yPosition += doc.heightOfString(section.content, { width: width - 100 }) + 20;
        }

        // Add charts if available
        if (section.chart && section.chart.png) {
          if (yPosition + 300 > height - 50) {
            doc.addPage();
            yPosition = 50;
          }
          
          doc.image(section.chart.png, 50, yPosition, {
            fit: [width - 100, 300],
            align: 'center'
          });
          yPosition += 320;
        }
      });
    }

    // Add footer
    doc.fontSize(10)
       .text('Generated by MaiFarm Trump Infog System', 50, height - 50, {
         align: 'center'
       });

    doc.end();

    const pdfBuffer = Buffer.concat(chunks);
    const optimizedBuffer = await this.optimizeOutput(pdfBuffer, 'pdf');

    return {
      format: 'pdf',
      data: optimizedBuffer,
      size: { width, height },
      fileSize: optimizedBuffer.length,
      metadata: {
        pages: doc.bufferedPageRange().count,
        createdAt: new Date(),
        ...options.metadata
      }
    };
  }

  private async exportAsSVG(data: any, options: ExportOptions): Promise<ExportResult> {
    const { width = 1920, height = 1080 } = options;
    
    let svgContent: string;
    
    if (data.svg) {
      svgContent = data.svg;
    } else {
      // Create a basic SVG structure
      svgContent = this.createBasicSVG(width, height, data);
    }

    // Optimize SVG
    const optimized = optimize(svgContent, {
      multipass: true,
      plugins: [
        {
          name: 'preset-default',
          params: {
            overrides: {
              removeViewBox: false,
              removeEmptyAttrs: false
            }
          }
        }
      ]
    });

    const svgBuffer = Buffer.from(optimized.data, 'utf-8');

    return {
      format: 'svg',
      data: optimized.data,
      size: { width, height },
      fileSize: svgBuffer.length,
      metadata: {
        optimized: true,
        originalSize: Buffer.from(svgContent).length,
        createdAt: new Date(),
        ...options.metadata
      }
    };
  }

  async convertSVGToPNG(svg: string, options?: ExportOptions): Promise<Buffer> {
    const { width = 1920, height = 1080, quality = 90 } = options || {};
    
    try {
      const svgBuffer = Buffer.from(svg);
      
      const pngBuffer = await sharp(svgBuffer)
        .resize(width, height, {
          fit: 'contain',
          background: { r: 255, g: 255, b: 255, alpha: 1 }
        })
        .png({ quality: Math.round(quality) })
        .toBuffer();
      
      return pngBuffer;
    } catch (error) {
      console.error('Error converting SVG to PNG:', error);
      // Fallback to placeholder
      return this.createPlaceholderPNG(width, height, 'Conversion Error');
    }
  }

  async generatePDF(content: any, options?: ExportOptions): Promise<Buffer> {
    return (await this.exportAsPDF(content, options || { format: 'pdf' })).data as Buffer;
  }

  async optimizeOutput(data: Buffer, format: string): Promise<Buffer> {
    try {
      switch (format) {
        case 'png':
          return await sharp(data)
            .png({ compressionLevel: 9, adaptiveFiltering: true })
            .toBuffer();
        
        case 'pdf':
          // PDF optimization would require additional libraries
          // For now, return as-is
          return data;
        
        default:
          return data;
      }
    } catch (error) {
      console.error('Error optimizing output:', error);
      return data;
    }
  }

  private async createPlaceholderPNG(width: number, height: number, text: string): Promise<Buffer> {
    const svg = `
      <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
        <rect width="${width}" height="${height}" fill="#f0f0f0"/>
        <text x="${width/2}" y="${height/2}" font-family="Arial" font-size="48" 
              text-anchor="middle" dominant-baseline="middle" fill="#666">
          ${text}
        </text>
      </svg>
    `;
    
    return sharp(Buffer.from(svg))
      .png()
      .toBuffer();
  }

  private createBasicSVG(width: number, height: number, data: any): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
      <svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" 
           xmlns="http://www.w3.org/2000/svg">
        <rect width="${width}" height="${height}" fill="#ffffff"/>
        <text x="${width/2}" y="80" font-family="Arial, sans-serif" font-size="48" 
              font-weight="bold" text-anchor="middle" fill="#1a1a1a">
          ${data.title || 'Trump News Analysis'}
        </text>
        <text x="${width/2}" y="130" font-family="Arial, sans-serif" font-size="20" 
              text-anchor="middle" fill="#666">
          Generated: ${new Date().toLocaleDateString()}
        </text>
        ${data.content ? `
          <foreignObject x="50" y="180" width="${width - 100}" height="${height - 230}">
            <div xmlns="http://www.w3.org/1999/xhtml" style="font-family: Arial; font-size: 16px; color: #333;">
              ${data.content}
            </div>
          </foreignObject>
        ` : ''}
      </svg>`;
  }
}

export const exportService = new ExportService();