import * as path from 'path';
import * as fs from 'fs/promises';
import { v4 as uuidv4 } from 'uuid';
import { pathConfig, getFarmWorkspacePath } from '../config/paths';
import { fileManager } from './fileManagerService';
import { logger } from '../utils/logger';
import { websocketManager } from '../websocket/websocketManager';
import { aiProviderManager, AIProvider, AIProviderConfig } from '../config/aiProviders';

/**
 * Workspace information
 */
export type WorkspaceMetadata = Record<string, unknown>;

export interface WorkspaceInfo {
  id: string;
  farmId: string;
  path: string;
  status: 'active' | 'archived' | 'locked';
  createdAt: Date;
  lastModified: Date;
  size: number;
  metadata: WorkspaceMetadata;
}

/**
 * Workspace template
 */
export interface WorkspaceTemplate {
  name: string;
  description: string;
  structure: {
    directories: string[];
    files: Array<{
      path: string;
      content: string;
    }>;
  };
  sharedResources?: string[];
}

export interface CreateWorkspaceOptions {
  template?: string;
  metadata?: WorkspaceMetadata;
  sharedResources?: string[];
  aiProvider?: AIProvider;
  initAI?: boolean;
  includeBarnAccess?: boolean;
}

/**
 * Workspace lock for concurrent access control
 */
interface WorkspaceLock {
  farmId: string;
  lockId: string;
  timestamp: Date;
  expiresAt: Date;
}

/**
 * Workspace Manager Service
 * Manages isolated workspaces for farms with complete isolation from MaiFarm codebase
 */
export class WorkspaceManager {
  private static instance: WorkspaceManager;
  private workspaces: Map<string, WorkspaceInfo> = new Map();
  private locks: Map<string, WorkspaceLock> = new Map();
  private templates: Map<string, WorkspaceTemplate> = new Map();
  private readonly LOCK_DURATION = 30 * 60 * 1000; // 30 minutes
  private readonly MAX_WORKSPACE_SIZE = 1 * 1024 * 1024 * 1024; // 1GB per workspace
  private cleanupInterval: NodeJS.Timeout | null = null;

  private constructor() {
    this.initializeTemplates();
    this.startCleanupScheduler();
  }

  static getInstance(): WorkspaceManager {
    if (!WorkspaceManager.instance) {
      WorkspaceManager.instance = new WorkspaceManager();
    }
    return WorkspaceManager.instance;
  }

  private initializeTemplates(): void {
    // Default workspace template
    this.templates.set('default', {
      name: 'Default Workspace',
      description: 'Standard isolated workspace for farm operations',
      structure: {
        directories: [
          'src',
          'src/components',
          'src/services',
          'src/utils',
          'tests',
          'docs',
          'output',
          'temp',
          '.config'
        ],
        files: [
          {
            path: 'README.md',
            content: `# Shared Farm Workspace

This is a SHARED workspace for ALL agents in this farm.
All agents collaborate in this single workspace.
All files created here are isolated from the main MaiFarm codebase.

## Important Notes
- This workspace is shared by ALL agents in the farm
- Agents should coordinate their file operations
- Use subdirectories for agent-specific work if needed
- The barn/ directory provides access to shared resources

## Structure
- \`src/\` - Source code generated by agents
- \`tests/\` - Test files
- \`docs/\` - Documentation
- \`output/\` - Farm output files
- \`temp/\` - Temporary files
- \`.config/\` - Configuration files

## Important
This workspace is completely isolated. Files here cannot affect MaiFarm.
`
          },
          {
            path: '.gitignore',
            content: `# Ignore all generated content
*
!.gitignore
!README.md
`
          },
          {
            path: '.config/workspace.json',
            content: JSON.stringify({
              version: '1.0.0',
              isolated: true,
              restrictions: {
                allowExternalAccess: false,
                maxFileSize: '100MB',
                allowedFileTypes: ['*']
              }
            }, null, 2)
          }
        ]
      }
    });

    // React app template
    this.templates.set('react-app', {
      name: 'React Application',
      description: 'Workspace for React application development',
      structure: {
        directories: [
          'src',
          'src/components',
          'src/hooks',
          'src/services',
          'src/styles',
          'public',
          'tests'
        ],
        files: [
          {
            path: 'package.json',
            content: JSON.stringify({
              name: 'farm-react-app',
              version: '1.0.0',
              private: true,
              dependencies: {},
              scripts: {
                start: 'react-scripts start',
                build: 'react-scripts build',
                test: 'react-scripts test'
              }
            }, null, 2)
          }
        ]
      }
    });

    // API service template
    this.templates.set('api-service', {
      name: 'API Service',
      description: 'Workspace for API service development',
      structure: {
        directories: [
          'src',
          'src/controllers',
          'src/models',
          'src/services',
          'src/middleware',
          'src/utils',
          'tests',
          'config'
        ],
        files: [
          {
            path: 'package.json',
            content: JSON.stringify({
              name: 'farm-api-service',
              version: '1.0.0',
              private: true,
              dependencies: {},
              scripts: {
                start: 'node src/index.js',
                dev: 'nodemon src/index.js',
                test: 'jest'
              }
            }, null, 2)
          }
        ]
      }
    });
  }

  /**
   * Create a new workspace for a farm
   */
  async createFarmWorkspace(
    farmId: string,
    options?: CreateWorkspaceOptions
  ): Promise<WorkspaceInfo> {
    try {
      logger.info(`[WorkspaceManager] Creating SHARED workspace for farm ${farmId} (all agents will use this workspace)`);
      
      // Check if workspace already exists
      if (this.workspaces.has(farmId)) {
        const existing = this.workspaces.get(farmId)!;
        if (existing.status === 'active') {
          logger.warn(`[WorkspaceManager] Workspace already exists for farm ${farmId}`);
          return existing;
        }
      }

      // Create workspace path - ONE workspace per farm, shared by ALL agents
      const workspacePath = getFarmWorkspacePath(farmId, false);
      await fileManager.ensureDirectory(workspacePath);

      // Apply template
      const templateName = options?.template || 'default';
      const template = this.templates.get(templateName);
      
      if (template) {
        await this.applyTemplate(workspacePath, template);
      }

      // Include shared resources if specified
      if (options?.sharedResources) {
        await this.includeSharedResources(workspacePath, options.sharedResources);
      }

      // CRITICAL: Set up Barn access for the workspace
      // This allows ALL agents in the farm to access Barn contents
      if (options?.includeBarnAccess !== false) { // Default to true
        await this.setupBarnAccess(workspacePath, farmId);
        logger.info(`[WorkspaceManager] Set up Barn access for workspace ${farmId}`);
      }

      // Initialize AI provider configuration if requested
      if (options?.initAI !== false) { // Default to true
        const provider = options?.aiProvider || aiProviderManager.getDefaultProvider();
        await this.initializeAIProvider(workspacePath, provider);
        logger.info(`[WorkspaceManager] Initialized AI provider ${provider} for workspace`);
      }

      // Create workspace info
      const workspace: WorkspaceInfo = {
        id: uuidv4(),
        farmId,
        path: workspacePath,
        status: 'active',
        createdAt: new Date(),
        lastModified: new Date(),
        size: 0,
        metadata: {
          template: templateName,
          aiProvider: options?.aiProvider || aiProviderManager.getDefaultProvider(),
          aiInitialized: options?.initAI !== false,
          ...options?.metadata
        }
      };

      // Store workspace info
      this.workspaces.set(farmId, workspace);
      
      // Write workspace metadata to disk
      await this.saveWorkspaceMetadata(workspace);

      // Emit workspace created event
      websocketManager.broadcast('workspace:created', {
        farmId,
        workspaceId: workspace.id,
        path: workspacePath,
        template: templateName
      });

      logger.info(`[WorkspaceManager] Created workspace ${workspace.id} for farm ${farmId}`);
      return workspace;
    } catch (error) {
      logger.error(`[WorkspaceManager] Failed to create workspace for farm ${farmId}:`, error);
      throw error;
    }
  }

  /**
   * Initialize AI provider configuration in workspace
   */
  private async initializeAIProvider(workspacePath: string, provider: AIProvider): Promise<void> {
    try {
      logger.info(`[WorkspaceManager] Setting up AI provider ${provider} in workspace`);
      await aiProviderManager.refreshApiKeys();
      
      // Get provider configuration
      const config = aiProviderManager.getProvider(provider);
      const providerEnv = aiProviderManager.getProviderEnvironment(provider);

      if (!config.apiKey) {
        logger.warn(`[WorkspaceManager] No API key available for provider ${provider} when initializing workspace ${workspacePath}`);
      }
      
      // Create .env file for the workspace
      const envContent = this.generateWorkspaceEnv(config, providerEnv);
      const envPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(workspacePath, '.env'));
      await fileManager.writeFile(envPath, envContent);
      
      // Create provider-specific configuration files
      await this.setupProviderConfig(workspacePath, provider, config);
      
      // Create workspace initialization script
      const initScript = this.generateInitScript(provider, config);
      const scriptPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(workspacePath, '.config', 'init.sh'));
      await fileManager.writeFile(scriptPath, initScript);
      
      // Make init script executable
      const fullScriptPath = path.join(pathConfig.getPath('MAIBARN_ROOT'), scriptPath);
      await fs.chmod(fullScriptPath, '755');
      
      logger.info(`[WorkspaceManager] AI provider ${provider} configuration complete`);
    } catch (error) {
      logger.error(`[WorkspaceManager] Failed to initialize AI provider ${provider}:`, error);
      throw error;
    }
  }

  /**
   * Apply a template to a workspace
   */
  private async applyTemplate(workspacePath: string, template: WorkspaceTemplate): Promise<void> {
    // Create directories
    for (const dir of template.structure.directories) {
      const dirPath = path.join(workspacePath, dir);
      await fileManager.ensureDirectory(dirPath);
    }

    // Create files
    for (const file of template.structure.files) {
      // Make path relative to MAIBARN_ROOT for fileManager
      const relativePath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(workspacePath, file.path));
      await fileManager.writeFile(relativePath, file.content);
    }
  }

  /**
   * Set up Barn access for a workspace
   * Creates a 'barn' directory in the workspace with symlinks or copies of Barn items
   */
  private async setupBarnAccess(workspacePath: string, farmId: string): Promise<void> {
    try {
      logger.info(`[WorkspaceManager] Setting up Barn access for farm ${farmId}`);
      
      // Create barn directory in workspace
      const barnAccessPath = path.join(workspacePath, 'barn');
      await fileManager.ensureDirectory(barnAccessPath);
      
      // Get the barn items path
      const barnItemsPath = pathConfig.getPath('BARN_ITEMS');
      
      // Check if barn items directory exists
      try {
        await fs.access(barnItemsPath);
      } catch {
        logger.warn(`[WorkspaceManager] Barn items directory does not exist yet: ${barnItemsPath}`);
        // Create empty barn structure
        await fileManager.ensureDirectory(barnItemsPath);
      }
      
      // Create a README in the barn access directory
      const barnReadme = `# Barn Access

This directory provides access to shared Barn resources.
All agents in this farm can access these resources.

## Structure
- \`items/\` - Shared artifacts and resources from previous farms
- \`catalog.json\` - Catalog of available barn items

## Usage
Agents can reference these resources in their tasks.
Resources are read-only to prevent accidental modification.
`;
      
      const readmePath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(barnAccessPath, 'README.md'));
      await fileManager.writeFile(readmePath, barnReadme);
      
      // Create symlink to barn items (preferred for efficiency)
      // This allows agents to access barn items without copying
      const itemsLinkPath = path.join(barnAccessPath, 'items');
      try {
        // Remove existing link if it exists
        try {
          await fs.unlink(itemsLinkPath);
        } catch {
          // Ignore if doesn't exist
        }
        
        // Create symlink to barn items
        await fs.symlink(barnItemsPath, itemsLinkPath, 'dir');
        logger.info(`[WorkspaceManager] Created symlink to Barn items for workspace ${farmId}`);
      } catch (error) {
        // Fallback: If symlink fails (e.g., on Windows), copy barn catalog instead
        logger.warn(`[WorkspaceManager] Could not create symlink, copying barn catalog instead:`, error);
        
        // Copy just the catalog file for reference
        const catalogPath = pathConfig.getPath('BARN_CATALOG');
        try {
          const catalogContent = await fs.readFile(catalogPath, 'utf-8');
          const workspaceCatalogPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(barnAccessPath, 'catalog.json'));
          await fileManager.writeFile(workspaceCatalogPath, catalogContent);
        } catch {
          // Create empty catalog if doesn't exist
          const emptyCatalog = JSON.stringify({ items: [], updated: new Date().toISOString() }, null, 2);
          const workspaceCatalogPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(barnAccessPath, 'catalog.json'));
          await fileManager.writeFile(workspaceCatalogPath, emptyCatalog);
        }
      }
      
      logger.info(`[WorkspaceManager] Barn access setup complete for farm ${farmId}`);
    } catch (error) {
      logger.error(`[WorkspaceManager] Failed to set up Barn access:`, error);
      // Don't throw - Barn access is optional
    }
  }

  /**
   * Generate workspace .env file content
   */
  private generateWorkspaceEnv(config: AIProviderConfig, providerEnv: Record<string, string>): string {
    const envLines = [
      '# MaiFarm Workspace Environment Configuration',
      '# This file is auto-generated - do not edit manually',
      '',
      '# AI Provider Configuration',
      `AI_PROVIDER=${config.provider}`,
      `AI_PROVIDER_ENABLED=true`,
      '',
    ];

    // Add provider-specific environment variables (only allow relevant AI provider vars)
    const allowedVarPrefixes = [
      'AI_PROVIDER', 'ANTHROPIC_', 'CLAUDE_', 'OPENAI_', 'LLAMA_', 'GPT_OSS_', 
      'OLLAMA_', 'USE_LLM_PROXY', 'LLM_PROXY_URL', 'DASHSCOPE_',
      // Core MaiFarm environment variables
      'PORT', 'VITE_', 'JWT_', 'BYPASS_AUTH', 'DB_', 'REDIS_', 'WS_',
      'LOG_', 'CORS_', 'RATE_LIMIT_', 'SESSION_SECRET', 'ENABLE_'
    ];
    
    Object.entries(providerEnv).forEach(([key, value]) => {
      // Only include variables that are relevant to AI providers or core functionality
      const isAllowed = allowedVarPrefixes.some(prefix => key.startsWith(prefix)) ||
                       key === 'AI_PROVIDER'; // Always include the AI provider setting
      
      if (isAllowed && value !== undefined && value !== '') {
        envLines.push(`${key}=${value}`);
      }
    });

    envLines.push('');
    envLines.push('# Workspace Configuration');
    envLines.push(`WORKSPACE_ISOLATED=true`);
    envLines.push(`WORKSPACE_AI_PROVIDER=${config.provider}`);

    return envLines.join('\n');
  }

  /**
   * Setup provider-specific configuration files
   */
  private async setupProviderConfig(workspacePath: string, provider: AIProvider, config: AIProviderConfig): Promise<void> {
    const configDir = path.join(workspacePath, '.config');
    
    switch (provider) {
      case AIProvider.CLAUDE:
        await this.setupClaudeConfig(configDir, config);
        break;
      case AIProvider.OPENAI:
        await this.setupOpenAIConfig(configDir, config);
        break;
      case AIProvider.LLAMA:
        await this.setupLlamaConfig(configDir, config);
        break;
      case AIProvider.GPT_OSS:
        await this.setupGptOssConfig(configDir, config);
        break;
    }
  }

  /**
   * Setup Claude CLI configuration
   */
  private async setupClaudeConfig(configDir: string, config: AIProviderConfig): Promise<void> {
    const claudeConfig = {
      api_key: config.apiKey,
      api_endpoint: config.apiEndpoint,
      model: config.model,
      max_tokens: config.maxTokens,
      temperature: config.temperature
    };
    
    const configPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(configDir, 'claude.json'));
    await fileManager.writeFile(configPath, JSON.stringify(claudeConfig, null, 2));
  }

  /**
   * Setup OpenAI CLI configuration
   */
  private async setupOpenAIConfig(configDir: string, config: AIProviderConfig): Promise<void> {
    const openaiConfig = {
      api_key: config.apiKey,
      api_base: config.apiEndpoint,
      model: config.model,
      max_tokens: config.maxTokens,
      temperature: config.temperature
    };
    
    const configPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(configDir, 'openai.json'));
    await fileManager.writeFile(configPath, JSON.stringify(openaiConfig, null, 2));
  }

  /**
   * Setup Llama configuration
   */
  private async setupLlamaConfig(configDir: string, config: AIProviderConfig): Promise<void> {
    const llamaConfig = {
      api_key: config.apiKey,
      api_endpoint: config.apiEndpoint,
      model: config.model,
      max_tokens: config.maxTokens,
      temperature: config.temperature,
      is_local: config.isLocal || false,
      ollama_model: config.ollamaModel
    };
    
    const configPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(configDir, 'llama.json'));
    await fileManager.writeFile(configPath, JSON.stringify(llamaConfig, null, 2));
  }

  /**
   * Setup GPT-OSS configuration
   */
  private async setupGptOssConfig(configDir: string, config: AIProviderConfig): Promise<void> {
    const gptOssConfig = {
      host: config.apiEndpoint,
      model: config.model,
      max_tokens: config.maxTokens,
      temperature: config.temperature,
      context_window: config.contextWindow
    };
    
    const configPath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(configDir, 'gpt-oss.json'));
    await fileManager.writeFile(configPath, JSON.stringify(gptOssConfig, null, 2));
  }

  /**
   * Generate workspace initialization script
   */
  private generateInitScript(provider: AIProvider, config: AIProviderConfig): string {
    const script = [
      '#!/bin/bash',
      '# MaiFarm Workspace Initialization Script',
      '# This script sets up the AI provider environment for this workspace',
      '# It ensures agents launched by orchestrator.py can access AI providers',
      '',
      'set -e',
      '',
      '# Get workspace directory',
      'WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
      'export WORKSPACE_DIR',
      '',
      '# Load workspace environment',
      'if [ -f "${WORKSPACE_DIR}/.env" ]; then',
      '  echo "Loading workspace environment from ${WORKSPACE_DIR}/.env"',
      '  set -a',
      '  source "${WORKSPACE_DIR}/.env"',
      '  set +a',
      'fi',
      '',
      '# Set up provider-specific environment',
      `echo "Initializing AI provider: ${provider}"`,
      '',
      '# Ensure AI provider is available in PATH and configured',
    ];

    switch (provider) {
      case AIProvider.CLAUDE:
        script.push(
          '# Claude CLI setup',
          'if command -v claude &> /dev/null; then',
          '  echo "✓ Claude CLI found at: $(which claude)"',
          '  export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}"',
          '  export CLAUDE_API_ENDPOINT="${CLAUDE_API_ENDPOINT}"',
          '  export CLAUDE_MODEL="${CLAUDE_MODEL}"',
          '  # Test Claude CLI connection',
          '  if [ -n "$ANTHROPIC_API_KEY" ]; then',
          '    echo "✓ Claude API key configured"',
          '  else',
          '    echo "⚠ Warning: ANTHROPIC_API_KEY not found in environment"',
          '  fi',
          'else',
          '  echo "⚠ Warning: Claude CLI not found in PATH"',
          '  echo "Agents may fail to launch. Please install Claude CLI."',
          'fi'
        );
        break;
      case AIProvider.OPENAI:
        script.push(
          '# OpenAI CLI setup',
          'if command -v openai &> /dev/null; then',
          '  echo "✓ OpenAI CLI found at: $(which openai)"',
          '  export OPENAI_API_KEY="${OPENAI_API_KEY}"',
          '  export OPENAI_API_ENDPOINT="${OPENAI_API_ENDPOINT}"',
          '  export OPENAI_MODEL="${OPENAI_MODEL}"',
          'else',
          '  echo "⚠ Warning: OpenAI CLI not found in PATH"',
          'fi'
        );
        break;
      case AIProvider.LLAMA:
        script.push(
          '# Llama/Ollama setup',
          'if command -v ollama &> /dev/null; then',
          '  echo "✓ Ollama found at: $(which ollama)"',
          '  export OLLAMA_HOST="${OLLAMA_HOST:-http://localhost:11434}"',
          '  export OLLAMA_MODEL="${OLLAMA_MODEL}"',
          '  # Test Ollama connection',
          '  if curl -s "${OLLAMA_HOST}/api/tags" > /dev/null 2>&1; then',
          '    echo "✓ Ollama server is accessible"',
          '  else',
          '    echo "⚠ Warning: Ollama server not accessible at ${OLLAMA_HOST}"',
          '  fi',
          'else',
          '  echo "⚠ Warning: Ollama not found in PATH"',
          'fi'
        );
        break;
      case AIProvider.GPT_OSS:
        script.push(
          '# GPT-OSS setup',
          'export GPT_OSS_HOST="${GPT_OSS_HOST}"',
          'export GPT_OSS_MODEL="${GPT_OSS_MODEL}"',
          'echo "✓ GPT-OSS endpoint: ${GPT_OSS_HOST}"',
          '# Test GPT-OSS connection',
          'if curl -s "${GPT_OSS_HOST}/health" > /dev/null 2>&1; then',
          '  echo "✓ GPT-OSS server is accessible"',
          'else',
          '  echo "⚠ Warning: GPT-OSS server not accessible at ${GPT_OSS_HOST}"',
          'fi'
        );
        break;
    }

    script.push(
      '',
      '# Create a profile script that can be sourced by agents',
      'cat > "${WORKSPACE_DIR}/.config/agent-profile.sh" << EOF',
      '#!/bin/bash',
      '# Auto-generated agent profile - sources workspace environment',
      'export WORKSPACE_DIR="${WORKSPACE_DIR}"',
      'if [ -f "${WORKSPACE_DIR}/.env" ]; then',
      '  set -a',
      '  source "${WORKSPACE_DIR}/.env"',
      '  set +a',
      'fi',
      'EOF',
      '',
      'chmod +x "${WORKSPACE_DIR}/.config/agent-profile.sh"',
      '',
      'echo "✓ Workspace initialized successfully"',
      'echo "  AI Provider: ${AI_PROVIDER}"',
      'echo "  Working directory: ${WORKSPACE_DIR}"',
      'echo "  Agent profile created at: ${WORKSPACE_DIR}/.config/agent-profile.sh"',
      '',
      `echo "  Provider endpoint: ${config.apiEndpoint}"`,
      `echo "  Provider model: ${config.model}"`,
      '',
      '# Provide guidance for orchestrator.py',
      'echo ""',
      'echo "📋 For orchestrator.py to use this workspace:"',
      'echo "   - Workspace directory: ${WORKSPACE_DIR}"',
      'echo "   - Environment file: ${WORKSPACE_DIR}/.env"',
      'echo "   - Agent profile: ${WORKSPACE_DIR}/.config/agent-profile.sh"',
      'echo ""'
    );

    return script.join('\n');
  }

  /**
   * Include shared resources in workspace
   */
  private async includeSharedResources(workspacePath: string, resources: string[]): Promise<void> {
    const sharedDir = path.join(workspacePath, '.shared');
    await fileManager.ensureDirectory(sharedDir);

    for (const resource of resources) {
      // Copy from barn templates or shared resources
      const sourcePath = path.join(pathConfig.getPath('BARN_TEMPLATES'), resource);
      const destPath = path.join(sharedDir, path.basename(resource));
      
      if (await fileManager.exists(sourcePath)) {
        await fileManager.copyFile(sourcePath, destPath);
      }
    }
  }

  /**
   * Get workspace path for a farm
   */
  getWorkspacePath(farmId: string): string {
    const workspace = this.workspaces.get(farmId);
    if (workspace) {
      return workspace.path;
    }
    return getFarmWorkspacePath(farmId, false);
  }

  /**
   * Get workspace info
   */
  async getWorkspaceInfo(farmId: string): Promise<WorkspaceInfo | null> {
    // Check cache first
    if (this.workspaces.has(farmId)) {
      return this.workspaces.get(farmId)!;
    }

    // Try to load from disk
    const workspacePath = getFarmWorkspacePath(farmId, false);
    const metadataPath = path.join(workspacePath, '.config', 'workspace.meta.json');
    
    if (await fileManager.exists(metadataPath)) {
      const content = await fileManager.readFile(metadataPath);
      const workspace = JSON.parse(content) as WorkspaceInfo;
      this.workspaces.set(farmId, workspace);
      return workspace;
    }

    return null;
  }

  /**
   * Lock a workspace for exclusive access
   */
  async lockWorkspace(farmId: string, duration?: number): Promise<string> {
    // Check if already locked
    if (this.locks.has(farmId)) {
      const lock = this.locks.get(farmId)!;
      if (lock.expiresAt > new Date()) {
        throw new Error(`Workspace for farm ${farmId} is already locked`);
      }
    }

    const lockId = uuidv4();
    const lock: WorkspaceLock = {
      farmId,
      lockId,
      timestamp: new Date(),
      expiresAt: new Date(Date.now() + (duration || this.LOCK_DURATION))
    };

    this.locks.set(farmId, lock);
    
    // Write lock file
    const lockPath = path.join(pathConfig.getPath('COORDINATION_LOCKS'), `${farmId}.lock`);
    await fileManager.writeFile(lockPath, JSON.stringify(lock));

    logger.info(`[WorkspaceManager] Locked workspace for farm ${farmId} with lock ${lockId}`);
    return lockId;
  }

  /**
   * Unlock a workspace
   */
  async unlockWorkspace(farmId: string, lockId: string): Promise<void> {
    const lock = this.locks.get(farmId);
    
    if (!lock || lock.lockId !== lockId) {
      throw new Error(`Invalid lock ID for farm ${farmId}`);
    }

    this.locks.delete(farmId);
    
    // Remove lock file
    const lockPath = path.join(pathConfig.getPath('COORDINATION_LOCKS'), `${farmId}.lock`);
    await fileManager.delete(lockPath);

    logger.info(`[WorkspaceManager] Unlocked workspace for farm ${farmId}`);
  }

  /**
   * Archive a workspace
   */
  async archiveWorkspace(farmId: string): Promise<void> {
    const workspace = await this.getWorkspaceInfo(farmId);
    if (!workspace) {
      throw new Error(`Workspace not found for farm ${farmId}`);
    }

    const sourcePath = workspace.path;
    const destPath = getFarmWorkspacePath(farmId, true); // archived = true

    // Move workspace to archive
    await fileManager.moveFile(sourcePath, destPath);

    // Update workspace status
    workspace.status = 'archived';
    workspace.path = destPath;
    workspace.lastModified = new Date();
    
    await this.saveWorkspaceMetadata(workspace);

    // Emit archive event
    websocketManager.broadcast('workspace:archived', {
      farmId,
      workspaceId: workspace.id
    });

    logger.info(`[WorkspaceManager] Archived workspace for farm ${farmId}`);
  }

  /**
   * Clean up a workspace
   */
  async cleanupWorkspace(farmId: string, archive: boolean = true): Promise<void> {
    try {
      const workspace = await this.getWorkspaceInfo(farmId);
      if (!workspace) {
        logger.warn(`[WorkspaceManager] No workspace found for farm ${farmId}`);
        return;
      }

      // Archive or delete
      if (archive) {
        await this.archiveWorkspace(farmId);
      } else {
        await fileManager.delete(workspace.path, true);
        this.workspaces.delete(farmId);
      }

      // Remove any locks
      this.locks.delete(farmId);

      // Emit cleanup event
      websocketManager.broadcast('workspace:cleaned', {
        farmId,
        archived: archive
      });

      logger.info(`[WorkspaceManager] Cleaned up workspace for farm ${farmId}`);
    } catch (error) {
      logger.error(`[WorkspaceManager] Failed to cleanup workspace for farm ${farmId}:`, error);
      throw error;
    }
  }

  /**
   * Check workspace health
   */
  async checkWorkspaceHealth(farmId: string): Promise<{
    healthy: boolean;
    size: number;
    issues: string[];
  }> {
    const workspace = await this.getWorkspaceInfo(farmId);
    if (!workspace) {
      return {
        healthy: false,
        size: 0,
        issues: ['Workspace not found']
      };
    }

    const issues: string[] = [];
    
    // Check size
    const size = await fileManager.getDirectorySize(workspace.path);
    if (size > this.MAX_WORKSPACE_SIZE) {
      issues.push(`Workspace exceeds size limit (${size} > ${this.MAX_WORKSPACE_SIZE})`);
    }

    // Check if path exists
    if (!await fileManager.exists(workspace.path)) {
      issues.push('Workspace path does not exist');
    }

    // Check for lock expiry
    const lock = this.locks.get(farmId);
    if (lock && lock.expiresAt < new Date()) {
      issues.push('Workspace lock has expired');
    }

    return {
      healthy: issues.length === 0,
      size,
      issues
    };
  }

  /**
   * Save workspace metadata to disk
   */
  private async saveWorkspaceMetadata(workspace: WorkspaceInfo): Promise<void> {
    const metadataPath = path.join(workspace.path, '.config', 'workspace.meta.json');
    await fileManager.ensureDirectory(path.dirname(metadataPath));
    // Make path relative to MAIBARN_ROOT for fileManager
    const relativePath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), metadataPath);
    await fileManager.writeFile(relativePath, JSON.stringify(workspace, null, 2));
  }

  /**
   * Start cleanup scheduler
   */
  private startCleanupScheduler(): void {
    // Run cleanup every hour
    this.cleanupInterval = setInterval(async () => {
      await this.performScheduledCleanup();
    }, 60 * 60 * 1000);
  }

  /**
   * Perform scheduled cleanup
   */
  private async performScheduledCleanup(): Promise<void> {
    try {
      logger.info('[WorkspaceManager] Starting scheduled cleanup');
      
      // Clean expired locks
      const now = new Date();
      for (const [farmId, lock] of this.locks.entries()) {
        if (lock.expiresAt < now) {
          this.locks.delete(farmId);
          logger.info(`[WorkspaceManager] Removed expired lock for farm ${farmId}`);
        }
      }

      // Clean old archived workspaces (older than 7 days)
      const archivedPath = pathConfig.getPath('FARM_WORKSPACES_ARCHIVED');
      const archivedItems = await fileManager.listDirectory(archivedPath);
      
      for (const item of archivedItems) {
        const itemPath = path.join(archivedPath, item);
        const stats = await fileManager.getStats(itemPath);
        
        if (stats && stats.mtime < new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)) {
          await fileManager.delete(itemPath, true);
          logger.info(`[WorkspaceManager] Deleted old archived workspace ${item}`);
        }
      }

      // Clean temporary files
      await fileManager.cleanupOldFiles(1); // Clean files older than 1 day

      logger.info('[WorkspaceManager] Scheduled cleanup completed');
    } catch (error) {
      logger.error('[WorkspaceManager] Scheduled cleanup failed:', error);
    }
  }

  /**
   * Get all active workspaces
   */
  async getAllActiveWorkspaces(): Promise<WorkspaceInfo[]> {
    const active: WorkspaceInfo[] = [];
    
    for (const workspace of this.workspaces.values()) {
      if (workspace.status === 'active') {
        active.push(workspace);
      }
    }
    
    return active;
  }

  /**
   * Get workspace statistics
   */
  async getWorkspaceStats(): Promise<{
    total: number;
    active: number;
    archived: number;
    locked: number;
    totalSize: number;
  }> {
    const stats = {
      total: this.workspaces.size,
      active: 0,
      archived: 0,
      locked: this.locks.size,
      totalSize: 0
    };

    for (const workspace of this.workspaces.values()) {
      if (workspace.status === 'active') stats.active++;
      if (workspace.status === 'archived') stats.archived++;
      stats.totalSize += workspace.size;
    }

    return stats;
  }

  /**
   * Cleanup on shutdown
   */
  destroy(): void {
    if (this.cleanupInterval) {
      clearInterval(this.cleanupInterval);
      this.cleanupInterval = null;
    }
  }
}

// Export singleton instance
export const workspaceManager = WorkspaceManager.getInstance();

// Export convenient helper functions
export const createFarmWorkspace = (farmId: string, options?: CreateWorkspaceOptions) => 
  workspaceManager.createFarmWorkspace(farmId, options);
export const getWorkspacePath = (farmId: string) => 
  workspaceManager.getWorkspacePath(farmId);
export const cleanupWorkspace = (farmId: string, archive?: boolean) => 
  workspaceManager.cleanupWorkspace(farmId, archive);
export const archiveWorkspace = (farmId: string) => 
  workspaceManager.archiveWorkspace(farmId);
export const checkWorkspaceHealth = (farmId: string) => 
  workspaceManager.checkWorkspaceHealth(farmId);
