import * as path from 'path';
import * as fs from 'fs/promises';
import { v4 as uuidv4 } from 'uuid';
import { pathConfig, getFarmWorkspacePath } from '../config/paths';
import { fileManager } from './fileManagerService';
import { logger } from '../utils/logger';
import { websocketManager } from '../websocket/websocketManager';

/**
 * Workspace information
 */
export interface WorkspaceInfo {
  id: string;
  farmId: string;
  path: string;
  status: 'active' | 'archived' | 'locked';
  createdAt: Date;
  lastModified: Date;
  size: number;
  metadata: Record<string, any>;
}

/**
 * Workspace template
 */
export interface WorkspaceTemplate {
  name: string;
  description: string;
  structure: {
    directories: string[];
    files: Array<{
      path: string;
      content: string;
    }>;
  };
  sharedResources?: string[];
}

/**
 * Workspace lock for concurrent access control
 */
interface WorkspaceLock {
  farmId: string;
  lockId: string;
  timestamp: Date;
  expiresAt: Date;
}

/**
 * Workspace Manager Service
 * Manages isolated workspaces for farms with complete isolation from MaiFarm codebase
 */
export class WorkspaceManager {
  private static instance: WorkspaceManager;
  private workspaces: Map<string, WorkspaceInfo> = new Map();
  private locks: Map<string, WorkspaceLock> = new Map();
  private templates: Map<string, WorkspaceTemplate> = new Map();
  private readonly LOCK_DURATION = 30 * 60 * 1000; // 30 minutes
  private readonly MAX_WORKSPACE_SIZE = 1 * 1024 * 1024 * 1024; // 1GB per workspace
  private cleanupInterval: NodeJS.Timeout | null = null;

  private constructor() {
    this.initializeTemplates();
    this.startCleanupScheduler();
  }

  static getInstance(): WorkspaceManager {
    if (!WorkspaceManager.instance) {
      WorkspaceManager.instance = new WorkspaceManager();
    }
    return WorkspaceManager.instance;
  }

  private initializeTemplates(): void {
    // Default workspace template
    this.templates.set('default', {
      name: 'Default Workspace',
      description: 'Standard isolated workspace for farm operations',
      structure: {
        directories: [
          'src',
          'src/components',
          'src/services',
          'src/utils',
          'tests',
          'docs',
          'output',
          'temp',
          '.config'
        ],
        files: [
          {
            path: 'README.md',
            content: `# Farm Workspace

This is an isolated workspace for farm operations.
All files created here are isolated from the main MaiFarm codebase.

## Structure
- \`src/\` - Source code generated by agents
- \`tests/\` - Test files
- \`docs/\` - Documentation
- \`output/\` - Farm output files
- \`temp/\` - Temporary files
- \`.config/\` - Configuration files

## Important
This workspace is completely isolated. Files here cannot affect MaiFarm.
`
          },
          {
            path: '.gitignore',
            content: `# Ignore all generated content
*
!.gitignore
!README.md
`
          },
          {
            path: '.config/workspace.json',
            content: JSON.stringify({
              version: '1.0.0',
              isolated: true,
              restrictions: {
                allowExternalAccess: false,
                maxFileSize: '100MB',
                allowedFileTypes: ['*']
              }
            }, null, 2)
          }
        ]
      }
    });

    // React app template
    this.templates.set('react-app', {
      name: 'React Application',
      description: 'Workspace for React application development',
      structure: {
        directories: [
          'src',
          'src/components',
          'src/hooks',
          'src/services',
          'src/styles',
          'public',
          'tests'
        ],
        files: [
          {
            path: 'package.json',
            content: JSON.stringify({
              name: 'farm-react-app',
              version: '1.0.0',
              private: true,
              dependencies: {},
              scripts: {
                start: 'react-scripts start',
                build: 'react-scripts build',
                test: 'react-scripts test'
              }
            }, null, 2)
          }
        ]
      }
    });

    // API service template
    this.templates.set('api-service', {
      name: 'API Service',
      description: 'Workspace for API service development',
      structure: {
        directories: [
          'src',
          'src/controllers',
          'src/models',
          'src/services',
          'src/middleware',
          'src/utils',
          'tests',
          'config'
        ],
        files: [
          {
            path: 'package.json',
            content: JSON.stringify({
              name: 'farm-api-service',
              version: '1.0.0',
              private: true,
              dependencies: {},
              scripts: {
                start: 'node src/index.js',
                dev: 'nodemon src/index.js',
                test: 'jest'
              }
            }, null, 2)
          }
        ]
      }
    });
  }

  /**
   * Create a new workspace for a farm
   */
  async createFarmWorkspace(
    farmId: string,
    options?: {
      template?: string;
      metadata?: Record<string, any>;
      sharedResources?: string[];
    }
  ): Promise<WorkspaceInfo> {
    try {
      logger.info(`[WorkspaceManager] Creating workspace for farm ${farmId}`);
      
      // Check if workspace already exists
      if (this.workspaces.has(farmId)) {
        const existing = this.workspaces.get(farmId)!;
        if (existing.status === 'active') {
          logger.warn(`[WorkspaceManager] Workspace already exists for farm ${farmId}`);
          return existing;
        }
      }

      // Create workspace path
      const workspacePath = getFarmWorkspacePath(farmId, false);
      await fileManager.ensureDirectory(workspacePath);

      // Apply template
      const templateName = options?.template || 'default';
      const template = this.templates.get(templateName);
      
      if (template) {
        await this.applyTemplate(workspacePath, template);
      }

      // Include shared resources if specified
      if (options?.sharedResources) {
        await this.includeSharedResources(workspacePath, options.sharedResources);
      }

      // Create workspace info
      const workspace: WorkspaceInfo = {
        id: uuidv4(),
        farmId,
        path: workspacePath,
        status: 'active',
        createdAt: new Date(),
        lastModified: new Date(),
        size: 0,
        metadata: {
          template: templateName,
          ...options?.metadata
        }
      };

      // Store workspace info
      this.workspaces.set(farmId, workspace);
      
      // Write workspace metadata to disk
      await this.saveWorkspaceMetadata(workspace);

      // Emit workspace created event
      websocketManager.broadcast('workspace:created', {
        farmId,
        workspaceId: workspace.id,
        path: workspacePath,
        template: templateName
      });

      logger.info(`[WorkspaceManager] Created workspace ${workspace.id} for farm ${farmId}`);
      return workspace;
    } catch (error) {
      logger.error(`[WorkspaceManager] Failed to create workspace for farm ${farmId}:`, error);
      throw error;
    }
  }

  /**
   * Apply a template to a workspace
   */
  private async applyTemplate(workspacePath: string, template: WorkspaceTemplate): Promise<void> {
    // Create directories
    for (const dir of template.structure.directories) {
      const dirPath = path.join(workspacePath, dir);
      await fileManager.ensureDirectory(dirPath);
    }

    // Create files
    for (const file of template.structure.files) {
      // Make path relative to MAIBARN_ROOT for fileManager
      const relativePath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), path.join(workspacePath, file.path));
      await fileManager.writeFile(relativePath, file.content);
    }
  }

  /**
   * Include shared resources in workspace
   */
  private async includeSharedResources(workspacePath: string, resources: string[]): Promise<void> {
    const sharedDir = path.join(workspacePath, '.shared');
    await fileManager.ensureDirectory(sharedDir);

    for (const resource of resources) {
      // Copy from barn templates or shared resources
      const sourcePath = path.join(pathConfig.getPath('BARN_TEMPLATES'), resource);
      const destPath = path.join(sharedDir, path.basename(resource));
      
      if (await fileManager.exists(sourcePath)) {
        await fileManager.copyFile(sourcePath, destPath);
      }
    }
  }

  /**
   * Get workspace path for a farm
   */
  getWorkspacePath(farmId: string): string {
    const workspace = this.workspaces.get(farmId);
    if (workspace) {
      return workspace.path;
    }
    return getFarmWorkspacePath(farmId, false);
  }

  /**
   * Get workspace info
   */
  async getWorkspaceInfo(farmId: string): Promise<WorkspaceInfo | null> {
    // Check cache first
    if (this.workspaces.has(farmId)) {
      return this.workspaces.get(farmId)!;
    }

    // Try to load from disk
    const workspacePath = getFarmWorkspacePath(farmId, false);
    const metadataPath = path.join(workspacePath, '.config', 'workspace.meta.json');
    
    if (await fileManager.exists(metadataPath)) {
      const content = await fileManager.readFile(metadataPath);
      const workspace = JSON.parse(content) as WorkspaceInfo;
      this.workspaces.set(farmId, workspace);
      return workspace;
    }

    return null;
  }

  /**
   * Lock a workspace for exclusive access
   */
  async lockWorkspace(farmId: string, duration?: number): Promise<string> {
    // Check if already locked
    if (this.locks.has(farmId)) {
      const lock = this.locks.get(farmId)!;
      if (lock.expiresAt > new Date()) {
        throw new Error(`Workspace for farm ${farmId} is already locked`);
      }
    }

    const lockId = uuidv4();
    const lock: WorkspaceLock = {
      farmId,
      lockId,
      timestamp: new Date(),
      expiresAt: new Date(Date.now() + (duration || this.LOCK_DURATION))
    };

    this.locks.set(farmId, lock);
    
    // Write lock file
    const lockPath = path.join(pathConfig.getPath('COORDINATION_LOCKS'), `${farmId}.lock`);
    await fileManager.writeFile(lockPath, JSON.stringify(lock));

    logger.info(`[WorkspaceManager] Locked workspace for farm ${farmId} with lock ${lockId}`);
    return lockId;
  }

  /**
   * Unlock a workspace
   */
  async unlockWorkspace(farmId: string, lockId: string): Promise<void> {
    const lock = this.locks.get(farmId);
    
    if (!lock || lock.lockId !== lockId) {
      throw new Error(`Invalid lock ID for farm ${farmId}`);
    }

    this.locks.delete(farmId);
    
    // Remove lock file
    const lockPath = path.join(pathConfig.getPath('COORDINATION_LOCKS'), `${farmId}.lock`);
    await fileManager.delete(lockPath);

    logger.info(`[WorkspaceManager] Unlocked workspace for farm ${farmId}`);
  }

  /**
   * Archive a workspace
   */
  async archiveWorkspace(farmId: string): Promise<void> {
    const workspace = await this.getWorkspaceInfo(farmId);
    if (!workspace) {
      throw new Error(`Workspace not found for farm ${farmId}`);
    }

    const sourcePath = workspace.path;
    const destPath = getFarmWorkspacePath(farmId, true); // archived = true

    // Move workspace to archive
    await fileManager.moveFile(sourcePath, destPath);

    // Update workspace status
    workspace.status = 'archived';
    workspace.path = destPath;
    workspace.lastModified = new Date();
    
    await this.saveWorkspaceMetadata(workspace);

    // Emit archive event
    websocketManager.broadcast('workspace:archived', {
      farmId,
      workspaceId: workspace.id
    });

    logger.info(`[WorkspaceManager] Archived workspace for farm ${farmId}`);
  }

  /**
   * Clean up a workspace
   */
  async cleanupWorkspace(farmId: string, archive: boolean = true): Promise<void> {
    try {
      const workspace = await this.getWorkspaceInfo(farmId);
      if (!workspace) {
        logger.warn(`[WorkspaceManager] No workspace found for farm ${farmId}`);
        return;
      }

      // Archive or delete
      if (archive) {
        await this.archiveWorkspace(farmId);
      } else {
        await fileManager.delete(workspace.path, true);
        this.workspaces.delete(farmId);
      }

      // Remove any locks
      this.locks.delete(farmId);

      // Emit cleanup event
      websocketManager.broadcast('workspace:cleaned', {
        farmId,
        archived: archive
      });

      logger.info(`[WorkspaceManager] Cleaned up workspace for farm ${farmId}`);
    } catch (error) {
      logger.error(`[WorkspaceManager] Failed to cleanup workspace for farm ${farmId}:`, error);
      throw error;
    }
  }

  /**
   * Check workspace health
   */
  async checkWorkspaceHealth(farmId: string): Promise<{
    healthy: boolean;
    size: number;
    issues: string[];
  }> {
    const workspace = await this.getWorkspaceInfo(farmId);
    if (!workspace) {
      return {
        healthy: false,
        size: 0,
        issues: ['Workspace not found']
      };
    }

    const issues: string[] = [];
    
    // Check size
    const size = await fileManager.getDirectorySize(workspace.path);
    if (size > this.MAX_WORKSPACE_SIZE) {
      issues.push(`Workspace exceeds size limit (${size} > ${this.MAX_WORKSPACE_SIZE})`);
    }

    // Check if path exists
    if (!await fileManager.exists(workspace.path)) {
      issues.push('Workspace path does not exist');
    }

    // Check for lock expiry
    const lock = this.locks.get(farmId);
    if (lock && lock.expiresAt < new Date()) {
      issues.push('Workspace lock has expired');
    }

    return {
      healthy: issues.length === 0,
      size,
      issues
    };
  }

  /**
   * Save workspace metadata to disk
   */
  private async saveWorkspaceMetadata(workspace: WorkspaceInfo): Promise<void> {
    const metadataPath = path.join(workspace.path, '.config', 'workspace.meta.json');
    await fileManager.ensureDirectory(path.dirname(metadataPath));
    // Make path relative to MAIBARN_ROOT for fileManager
    const relativePath = path.relative(pathConfig.getPath('MAIBARN_ROOT'), metadataPath);
    await fileManager.writeFile(relativePath, JSON.stringify(workspace, null, 2));
  }

  /**
   * Start cleanup scheduler
   */
  private startCleanupScheduler(): void {
    // Run cleanup every hour
    this.cleanupInterval = setInterval(async () => {
      await this.performScheduledCleanup();
    }, 60 * 60 * 1000);
  }

  /**
   * Perform scheduled cleanup
   */
  private async performScheduledCleanup(): Promise<void> {
    try {
      logger.info('[WorkspaceManager] Starting scheduled cleanup');
      
      // Clean expired locks
      const now = new Date();
      for (const [farmId, lock] of this.locks.entries()) {
        if (lock.expiresAt < now) {
          this.locks.delete(farmId);
          logger.info(`[WorkspaceManager] Removed expired lock for farm ${farmId}`);
        }
      }

      // Clean old archived workspaces (older than 7 days)
      const archivedPath = pathConfig.getPath('FARM_WORKSPACES_ARCHIVED');
      const archivedItems = await fileManager.listDirectory(archivedPath);
      
      for (const item of archivedItems) {
        const itemPath = path.join(archivedPath, item);
        const stats = await fileManager.getStats(itemPath);
        
        if (stats && stats.mtime < new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)) {
          await fileManager.delete(itemPath, true);
          logger.info(`[WorkspaceManager] Deleted old archived workspace ${item}`);
        }
      }

      // Clean temporary files
      await fileManager.cleanupOldFiles(1); // Clean files older than 1 day

      logger.info('[WorkspaceManager] Scheduled cleanup completed');
    } catch (error) {
      logger.error('[WorkspaceManager] Scheduled cleanup failed:', error);
    }
  }

  /**
   * Get all active workspaces
   */
  async getAllActiveWorkspaces(): Promise<WorkspaceInfo[]> {
    const active: WorkspaceInfo[] = [];
    
    for (const workspace of this.workspaces.values()) {
      if (workspace.status === 'active') {
        active.push(workspace);
      }
    }
    
    return active;
  }

  /**
   * Get workspace statistics
   */
  async getWorkspaceStats(): Promise<{
    total: number;
    active: number;
    archived: number;
    locked: number;
    totalSize: number;
  }> {
    const stats = {
      total: this.workspaces.size,
      active: 0,
      archived: 0,
      locked: this.locks.size,
      totalSize: 0
    };

    for (const workspace of this.workspaces.values()) {
      if (workspace.status === 'active') stats.active++;
      if (workspace.status === 'archived') stats.archived++;
      stats.totalSize += workspace.size;
    }

    return stats;
  }

  /**
   * Cleanup on shutdown
   */
  destroy(): void {
    if (this.cleanupInterval) {
      clearInterval(this.cleanupInterval);
      this.cleanupInterval = null;
    }
  }
}

// Export singleton instance
export const workspaceManager = WorkspaceManager.getInstance();

// Export convenient helper functions
export const createFarmWorkspace = (farmId: string, options?: any) => 
  workspaceManager.createFarmWorkspace(farmId, options);
export const getWorkspacePath = (farmId: string) => 
  workspaceManager.getWorkspacePath(farmId);
export const cleanupWorkspace = (farmId: string, archive?: boolean) => 
  workspaceManager.cleanupWorkspace(farmId, archive);
export const archiveWorkspace = (farmId: string) => 
  workspaceManager.archiveWorkspace(farmId);
export const checkWorkspaceHealth = (farmId: string) => 
  workspaceManager.checkWorkspaceHealth(farmId);