/**
 * Causal Graph Visualization Component
 *
 * Displays the causal model graph generated by DEMOCRITUS-inspired extraction
 * (arxiv 2512.07796) during the MODELING phase.
 *
 * Shows:
 * - Directed graph of causal relationships
 * - Nodes with type-based coloring
 * - Edges with relationship labels
 * - Topological ordering path
 * - Conflict highlighting
 * - Cycle detection warnings
 */

import React, { useEffect, useRef, useState, useCallback } from 'react';
import * as d3 from 'd3';
import {
  AlertTriangle,
  CheckCircle,
  GitBranch,
  Zap,
  Target,
  Box,
  Lock,
  Milestone,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  Info,
  List,
  Network,
} from 'lucide-react';

// Types matching the backend CausalModel interfaces
type CausalRelationship =
  | 'causes'
  | 'enables'
  | 'prevents'
  | 'requires'
  | 'follows'
  | 'produces'
  | 'consumes'
  | 'modifies'
  | 'triggers';

type CausalNodeType =
  | 'action'
  | 'state'
  | 'goal'
  | 'entity'
  | 'constraint'
  | 'milestone';

type ConflictType =
  | 'contradiction'
  | 'inconsistency'
  | 'ambiguity'
  | 'cycle';

interface CausalNode {
  id: string;
  label: string;
  type: CausalNodeType;
  inDegree: number;
  outDegree: number;
  isRoot: boolean;
  isLeaf: boolean;
  topologicalIndex?: number;
  properties?: Record<string, unknown>;
}

interface CausalEdge {
  id: string;
  source: string;
  target: string;
  weight: number;
  relationship: CausalRelationship;
  tripleId: string;
  critical?: boolean;
}

interface CausalConflict {
  id: string;
  tripleIds: string[];
  type: ConflictType;
  description: string;
  resolved: boolean;
}

interface CausalGraph {
  nodes: CausalNode[];
  edges: CausalEdge[];
  topologicalOrder: string[];
  isDAG: boolean;
  cycles?: string[][];
  criticalPath?: string[];
  stats: {
    nodeCount: number;
    edgeCount: number;
    rootCount: number;
    leafCount: number;
    maxDepth: number;
    avgConfidence: number;
    componentCount: number;
  };
}

interface CausalModel {
  id: string;
  farmId: string;
  graph: CausalGraph;
  conflicts: CausalConflict[];
  topologicalOrder: string[];
  conflictResolutionStatus: string;
}

interface CausalGraphVisualizationProps {
  model: CausalModel;
  width?: number;
  height?: number;
  compact?: boolean;
}

// D3 simulation node type
interface SimNode extends d3.SimulationNodeDatum {
  id: string;
  label: string;
  type: CausalNodeType;
  isRoot: boolean;
  isLeaf: boolean;
  topologicalIndex?: number;
  inDegree: number;
  outDegree: number;
}

// D3 simulation link type
interface SimLink extends d3.SimulationLinkDatum<SimNode> {
  id: string;
  relationship: CausalRelationship;
  weight: number;
  critical?: boolean;
}

// Node type colors
const NODE_COLORS: Record<CausalNodeType, string> = {
  action: '#f97316',    // orange
  state: '#3b82f6',     // blue
  goal: '#10b981',      // green
  entity: '#8b5cf6',    // purple
  constraint: '#ef4444', // red
  milestone: '#f59e0b', // amber
};

// Relationship colors
const RELATIONSHIP_COLORS: Record<CausalRelationship, string> = {
  causes: '#374151',
  enables: '#059669',
  prevents: '#dc2626',
  requires: '#7c3aed',
  follows: '#6b7280',
  produces: '#059669',
  consumes: '#dc2626',
  modifies: '#f59e0b',
  triggers: '#3b82f6',
};

// Node type icons
const NodeTypeIcon: React.FC<{ type: CausalNodeType; className?: string }> = ({
  type,
  className = 'h-4 w-4',
}) => {
  switch (type) {
    case 'action':
      return <Zap className={className} />;
    case 'state':
      return <Box className={className} />;
    case 'goal':
      return <Target className={className} />;
    case 'entity':
      return <GitBranch className={className} />;
    case 'constraint':
      return <Lock className={className} />;
    case 'milestone':
      return <Milestone className={className} />;
    default:
      return <Box className={className} />;
  }
};

// Compact statistics view
const CompactStats: React.FC<{ model: CausalModel }> = ({ model }) => {
  const { graph, conflicts } = model;
  const unresolvedConflicts = conflicts.filter((c) => !c.resolved).length;

  return (
    <div className="bg-white rounded-lg shadow p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-semibold text-lg flex items-center gap-2">
          <Network className="h-5 w-5 text-blue-500" />
          Causal Graph
        </h3>
        <div className="flex items-center gap-2">
          {graph.isDAG ? (
            <CheckCircle className="h-5 w-5 text-green-500" />
          ) : (
            <AlertTriangle className="h-5 w-5 text-yellow-500" />
          )}
          <span className={graph.isDAG ? 'text-green-600' : 'text-yellow-600'}>
            {graph.isDAG ? 'DAG' : 'Has Cycles'}
          </span>
        </div>
      </div>
      <div className="grid grid-cols-4 gap-2 text-center text-sm">
        <div className="bg-gray-50 rounded p-2">
          <div className="font-bold text-lg">{graph.stats.nodeCount}</div>
          <div className="text-gray-600">Nodes</div>
        </div>
        <div className="bg-gray-50 rounded p-2">
          <div className="font-bold text-lg">{graph.stats.edgeCount}</div>
          <div className="text-gray-600">Edges</div>
        </div>
        <div className="bg-gray-50 rounded p-2">
          <div className="font-bold text-lg">{conflicts.length}</div>
          <div className="text-gray-600">Conflicts</div>
        </div>
        <div className="bg-gray-50 rounded p-2">
          <div className="font-bold text-lg">{unresolvedConflicts}</div>
          <div className="text-gray-600">Unresolved</div>
        </div>
      </div>
    </div>
  );
};

// Topological order list
const TopologicalOrderList: React.FC<{
  order: string[];
  nodes: CausalNode[];
  criticalPath?: string[];
}> = ({ order, nodes, criticalPath }) => {
  const nodeMap = new Map(nodes.map((n) => [n.id, n]));
  const criticalSet = new Set(criticalPath || []);

  return (
    <div className="bg-gray-50 rounded-lg p-3 max-h-40 overflow-y-auto">
      <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center gap-1">
        <List className="h-4 w-4" />
        Execution Order
      </h4>
      <ol className="space-y-1 text-sm">
        {order.map((nodeId, index) => {
          const node = nodeMap.get(nodeId);
          const isCritical = criticalSet.has(nodeId);
          return (
            <li
              key={nodeId}
              className={`flex items-center gap-2 p-1 rounded ${
                isCritical ? 'bg-red-50 border-l-2 border-red-400' : ''
              }`}
            >
              <span className="w-5 h-5 flex items-center justify-center bg-gray-200 rounded-full text-xs font-medium">
                {index + 1}
              </span>
              <span
                className="w-3 h-3 rounded-full"
                style={{ backgroundColor: NODE_COLORS[node?.type || 'entity'] }}
              />
              <span className={isCritical ? 'font-medium' : ''}>
                {node?.label || nodeId}
              </span>
              {isCritical && (
                <span className="text-xs text-red-600 ml-auto">critical</span>
              )}
            </li>
          );
        })}
      </ol>
    </div>
  );
};

// Conflict list
const ConflictList: React.FC<{ conflicts: CausalConflict[] }> = ({
  conflicts,
}) => {
  if (conflicts.length === 0) {
    return (
      <div className="text-sm text-gray-500 flex items-center gap-2">
        <CheckCircle className="h-4 w-4 text-green-500" />
        No conflicts detected
      </div>
    );
  }

  return (
    <div className="space-y-2 max-h-40 overflow-y-auto">
      {conflicts.map((conflict) => (
        <div
          key={conflict.id}
          className={`p-2 rounded border ${
            conflict.resolved
              ? 'border-green-200 bg-green-50'
              : 'border-red-200 bg-red-50'
          }`}
        >
          <div className="flex items-center justify-between">
            <span
              className={`text-xs font-medium px-2 py-0.5 rounded ${
                conflict.type === 'contradiction'
                  ? 'bg-red-100 text-red-800'
                  : conflict.type === 'cycle'
                  ? 'bg-yellow-100 text-yellow-800'
                  : 'bg-orange-100 text-orange-800'
              }`}
            >
              {conflict.type}
            </span>
            {conflict.resolved ? (
              <CheckCircle className="h-4 w-4 text-green-500" />
            ) : (
              <AlertTriangle className="h-4 w-4 text-red-500" />
            )}
          </div>
          <p className="text-sm mt-1 text-gray-700">{conflict.description}</p>
        </div>
      ))}
    </div>
  );
};

// Main graph visualization component
export const CausalGraphVisualization: React.FC<CausalGraphVisualizationProps> = ({
  model,
  width = 600,
  height = 400,
  compact = false,
}) => {
  const svgRef = useRef<SVGSVGElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [selectedNode, setSelectedNode] = useState<SimNode | null>(null);
  const [view, setView] = useState<'graph' | 'list'>('graph');
  const [zoomLevel, setZoomLevel] = useState(1);

  const zoomRef = useRef<d3.ZoomBehavior<SVGSVGElement, unknown> | null>(null);

  // Initialize D3 force simulation
  useEffect(() => {
    if (!svgRef.current || !model || compact) return;

    const svg = d3.select(svgRef.current);
    svg.selectAll('*').remove();

    const { graph } = model;
    if (!graph || !graph.nodes || graph.nodes.length === 0) return;

    // Create simulation data
    const nodes: SimNode[] = graph.nodes.map((n) => ({
      ...n,
      x: width / 2,
      y: height / 2,
    }));

    const nodeMap = new Map(nodes.map((n) => [n.id, n]));

    const links: SimLink[] = graph.edges
      .map((e) => ({
        id: e.id,
        source: nodeMap.get(e.source) || e.source,
        target: nodeMap.get(e.target) || e.target,
        relationship: e.relationship,
        weight: e.weight,
        critical: e.critical,
      }))
      .filter((l) => l.source && l.target) as SimLink[];

    // Create zoom behavior
    const zoom = d3
      .zoom<SVGSVGElement, unknown>()
      .scaleExtent([0.2, 3])
      .on('zoom', (event) => {
        g.attr('transform', event.transform);
        setZoomLevel(event.transform.k);
      });

    zoomRef.current = zoom;
    svg.call(zoom);

    // Create main group for zoom/pan
    const g = svg.append('g');

    // Define arrow markers for edges
    const defs = svg.append('defs');

    Object.entries(RELATIONSHIP_COLORS).forEach(([rel, color]) => {
      defs
        .append('marker')
        .attr('id', `arrow-${rel}`)
        .attr('viewBox', '0 -5 10 10')
        .attr('refX', 20)
        .attr('refY', 0)
        .attr('markerWidth', 6)
        .attr('markerHeight', 6)
        .attr('orient', 'auto')
        .append('path')
        .attr('fill', color)
        .attr('d', 'M0,-5L10,0L0,5');
    });

    // Create force simulation
    const simulation = d3
      .forceSimulation<SimNode>(nodes)
      .force(
        'link',
        d3
          .forceLink<SimNode, SimLink>(links)
          .id((d) => d.id)
          .distance(100)
      )
      .force('charge', d3.forceManyBody().strength(-300))
      .force('center', d3.forceCenter(width / 2, height / 2))
      .force('collision', d3.forceCollide().radius(30));

    // Draw edges
    const link = g
      .append('g')
      .attr('class', 'links')
      .selectAll('line')
      .data(links)
      .enter()
      .append('line')
      .attr('stroke', (d) => RELATIONSHIP_COLORS[d.relationship])
      .attr('stroke-width', (d) => (d.critical ? 3 : 1.5))
      .attr('stroke-dasharray', (d) =>
        d.relationship === 'prevents' ? '5,5' : 'none'
      )
      .attr('marker-end', (d) => `url(#arrow-${d.relationship})`);

    // Draw edge labels
    const linkLabels = g
      .append('g')
      .attr('class', 'link-labels')
      .selectAll('text')
      .data(links)
      .enter()
      .append('text')
      .attr('font-size', '10px')
      .attr('fill', '#6b7280')
      .attr('text-anchor', 'middle')
      .text((d) => d.relationship);

    // Draw nodes
    const node = g
      .append('g')
      .attr('class', 'nodes')
      .selectAll('g')
      .data(nodes)
      .enter()
      .append('g')
      .attr('cursor', 'pointer')
      .call(
        d3
          .drag<SVGGElement, SimNode>()
          .on('start', (event, d) => {
            if (!event.active) simulation.alphaTarget(0.3).restart();
            d.fx = d.x;
            d.fy = d.y;
          })
          .on('drag', (event, d) => {
            d.fx = event.x;
            d.fy = event.y;
          })
          .on('end', (event, d) => {
            if (!event.active) simulation.alphaTarget(0);
            d.fx = null;
            d.fy = null;
          })
      )
      .on('click', (event, d) => {
        setSelectedNode(selectedNode?.id === d.id ? null : d);
      });

    // Node circles
    node
      .append('circle')
      .attr('r', (d) => (d.isRoot || d.isLeaf ? 15 : 12))
      .attr('fill', (d) => NODE_COLORS[d.type])
      .attr('stroke', (d) =>
        model.graph.criticalPath?.includes(d.id) ? '#dc2626' : '#fff'
      )
      .attr('stroke-width', (d) =>
        model.graph.criticalPath?.includes(d.id) ? 3 : 2
      );

    // Node labels
    node
      .append('text')
      .attr('dy', 25)
      .attr('text-anchor', 'middle')
      .attr('font-size', '11px')
      .attr('fill', '#374151')
      .text((d) => (d.label.length > 15 ? d.label.slice(0, 15) + '...' : d.label));

    // Topological index badges
    node
      .filter((d) => d.topologicalIndex !== undefined && d.topologicalIndex >= 0)
      .append('text')
      .attr('dy', -20)
      .attr('text-anchor', 'middle')
      .attr('font-size', '10px')
      .attr('fill', '#fff')
      .attr('font-weight', 'bold')
      .text((d) => `#${(d.topologicalIndex ?? 0) + 1}`);

    // Tick function
    simulation.on('tick', () => {
      link
        .attr('x1', (d) => (d.source as SimNode).x ?? 0)
        .attr('y1', (d) => (d.source as SimNode).y ?? 0)
        .attr('x2', (d) => (d.target as SimNode).x ?? 0)
        .attr('y2', (d) => (d.target as SimNode).y ?? 0);

      linkLabels
        .attr('x', (d) => {
          const sx = (d.source as SimNode).x ?? 0;
          const tx = (d.target as SimNode).x ?? 0;
          return (sx + tx) / 2;
        })
        .attr('y', (d) => {
          const sy = (d.source as SimNode).y ?? 0;
          const ty = (d.target as SimNode).y ?? 0;
          return (sy + ty) / 2 - 5;
        });

      node.attr('transform', (d) => `translate(${d.x ?? 0},${d.y ?? 0})`);
    });

    // Cleanup
    return () => {
      simulation.stop();
    };
  }, [model, width, height, compact, selectedNode]);

  // Zoom controls
  const handleZoomIn = useCallback(() => {
    if (svgRef.current && zoomRef.current) {
      d3.select(svgRef.current)
        .transition()
        .duration(300)
        .call(zoomRef.current.scaleBy, 1.3);
    }
  }, []);

  const handleZoomOut = useCallback(() => {
    if (svgRef.current && zoomRef.current) {
      d3.select(svgRef.current)
        .transition()
        .duration(300)
        .call(zoomRef.current.scaleBy, 0.7);
    }
  }, []);

  const handleResetZoom = useCallback(() => {
    if (svgRef.current && zoomRef.current) {
      d3.select(svgRef.current)
        .transition()
        .duration(300)
        .call(zoomRef.current.transform, d3.zoomIdentity);
    }
  }, []);

  if (!model) {
    return (
      <div className="text-gray-500 text-center py-4">
        No causal model available
      </div>
    );
  }

  if (compact) {
    return <CompactStats model={model} />;
  }

  const { graph, conflicts, topologicalOrder } = model;
  const unresolvedConflicts = conflicts.filter((c) => !c.resolved).length;

  return (
    <div className="bg-white rounded-lg shadow-md p-6 space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b pb-4">
        <div>
          <h2 className="text-xl font-bold flex items-center gap-2">
            <Network className="h-6 w-6 text-blue-500" />
            Causal Graph
          </h2>
          <p className="text-sm text-gray-600">
            DEMOCRITUS Pipeline (arxiv 2512.07796)
          </p>
        </div>
        <div className="flex items-center gap-4">
          {/* View toggle */}
          <div className="flex bg-gray-100 rounded-lg p-1">
            <button
              onClick={() => setView('graph')}
              className={`px-3 py-1 text-sm rounded ${
                view === 'graph'
                  ? 'bg-white shadow text-blue-600'
                  : 'text-gray-600'
              }`}
            >
              Graph
            </button>
            <button
              onClick={() => setView('list')}
              className={`px-3 py-1 text-sm rounded ${
                view === 'list'
                  ? 'bg-white shadow text-blue-600'
                  : 'text-gray-600'
              }`}
            >
              List
            </button>
          </div>
          {/* DAG status */}
          <div className="flex items-center gap-2">
            {graph.isDAG ? (
              <CheckCircle className="h-5 w-5 text-green-500" />
            ) : (
              <AlertTriangle className="h-5 w-5 text-yellow-500" />
            )}
            <span
              className={`font-medium ${
                graph.isDAG ? 'text-green-600' : 'text-yellow-600'
              }`}
            >
              {graph.isDAG ? 'Valid DAG' : 'Contains Cycles'}
            </span>
          </div>
        </div>
      </div>

      {/* Statistics bar */}
      <div className="grid grid-cols-6 gap-2 text-center text-sm">
        <div className="bg-blue-50 rounded p-2">
          <div className="font-bold text-lg text-blue-700">
            {graph.stats.nodeCount}
          </div>
          <div className="text-blue-600">Nodes</div>
        </div>
        <div className="bg-purple-50 rounded p-2">
          <div className="font-bold text-lg text-purple-700">
            {graph.stats.edgeCount}
          </div>
          <div className="text-purple-600">Edges</div>
        </div>
        <div className="bg-green-50 rounded p-2">
          <div className="font-bold text-lg text-green-700">
            {graph.stats.rootCount}
          </div>
          <div className="text-green-600">Roots</div>
        </div>
        <div className="bg-orange-50 rounded p-2">
          <div className="font-bold text-lg text-orange-700">
            {graph.stats.leafCount}
          </div>
          <div className="text-orange-600">Leaves</div>
        </div>
        <div className="bg-gray-50 rounded p-2">
          <div className="font-bold text-lg text-gray-700">
            {graph.stats.maxDepth}
          </div>
          <div className="text-gray-600">Depth</div>
        </div>
        <div
          className={`rounded p-2 ${
            unresolvedConflicts > 0 ? 'bg-red-50' : 'bg-green-50'
          }`}
        >
          <div
            className={`font-bold text-lg ${
              unresolvedConflicts > 0 ? 'text-red-700' : 'text-green-700'
            }`}
          >
            {unresolvedConflicts}
          </div>
          <div
            className={unresolvedConflicts > 0 ? 'text-red-600' : 'text-green-600'}
          >
            Conflicts
          </div>
        </div>
      </div>

      {/* Graph view */}
      {view === 'graph' && (
        <div ref={containerRef} className="relative border rounded-lg bg-gray-50">
          {/* Zoom controls */}
          <div className="absolute top-2 right-2 flex flex-col gap-1 z-10">
            <button
              onClick={handleZoomIn}
              className="p-1.5 bg-white rounded shadow hover:bg-gray-50"
              title="Zoom in"
            >
              <ZoomIn className="h-4 w-4" />
            </button>
            <button
              onClick={handleZoomOut}
              className="p-1.5 bg-white rounded shadow hover:bg-gray-50"
              title="Zoom out"
            >
              <ZoomOut className="h-4 w-4" />
            </button>
            <button
              onClick={handleResetZoom}
              className="p-1.5 bg-white rounded shadow hover:bg-gray-50"
              title="Reset zoom"
            >
              <RotateCcw className="h-4 w-4" />
            </button>
          </div>

          {/* Zoom level indicator */}
          <div className="absolute bottom-2 right-2 text-xs text-gray-500 bg-white px-2 py-1 rounded shadow">
            {(zoomLevel * 100).toFixed(0)}%
          </div>

          {/* SVG canvas */}
          <svg ref={svgRef} width={width} height={height} className="w-full" />

          {/* Legend */}
          <div className="absolute bottom-2 left-2 bg-white p-2 rounded shadow text-xs space-y-1">
            <div className="font-medium mb-1">Node Types</div>
            <div className="grid grid-cols-2 gap-x-4 gap-y-1">
              {Object.entries(NODE_COLORS).map(([type, color]) => (
                <div key={type} className="flex items-center gap-1">
                  <span
                    className="w-3 h-3 rounded-full"
                    style={{ backgroundColor: color }}
                  />
                  <span>{type}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* List view */}
      {view === 'list' && (
        <div className="grid grid-cols-2 gap-4">
          <TopologicalOrderList
            order={topologicalOrder}
            nodes={graph.nodes}
            criticalPath={graph.criticalPath}
          />
          <div className="bg-gray-50 rounded-lg p-3">
            <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center gap-1">
              <AlertTriangle className="h-4 w-4" />
              Conflicts ({conflicts.length})
            </h4>
            <ConflictList conflicts={conflicts} />
          </div>
        </div>
      )}

      {/* Selected node details */}
      {selectedNode && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <NodeTypeIcon type={selectedNode.type} className="h-5 w-5" />
              <span className="font-semibold">{selectedNode.label}</span>
              <span
                className="px-2 py-0.5 rounded text-xs"
                style={{
                  backgroundColor: NODE_COLORS[selectedNode.type],
                  color: 'white',
                }}
              >
                {selectedNode.type}
              </span>
            </div>
            <button
              onClick={() => setSelectedNode(null)}
              className="text-gray-500 hover:text-gray-700"
            >
              ×
            </button>
          </div>
          <div className="grid grid-cols-4 gap-2 text-sm">
            <div>
              <span className="text-gray-500">Incoming:</span>{' '}
              <span className="font-medium">{selectedNode.inDegree}</span>
            </div>
            <div>
              <span className="text-gray-500">Outgoing:</span>{' '}
              <span className="font-medium">{selectedNode.outDegree}</span>
            </div>
            <div>
              <span className="text-gray-500">Order:</span>{' '}
              <span className="font-medium">
                {selectedNode.topologicalIndex !== undefined
                  ? `#${selectedNode.topologicalIndex + 1}`
                  : 'N/A'}
              </span>
            </div>
            <div>
              <span className="text-gray-500">Role:</span>{' '}
              <span className="font-medium">
                {selectedNode.isRoot
                  ? 'Root'
                  : selectedNode.isLeaf
                  ? 'Leaf'
                  : 'Internal'}
              </span>
            </div>
          </div>
        </div>
      )}

      {/* Cycle warning */}
      {!graph.isDAG && graph.cycles && graph.cycles.length > 0 && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle className="h-5 w-5 text-yellow-600" />
            <span className="font-semibold text-yellow-800">
              Cycles Detected ({graph.cycles.length})
            </span>
          </div>
          <ul className="text-sm text-yellow-700 space-y-1">
            {graph.cycles.slice(0, 3).map((cycle, i) => (
              <li key={i} className="flex items-center gap-1">
                <span className="font-mono">{cycle.join(' → ')} → ...</span>
              </li>
            ))}
            {graph.cycles.length > 3 && (
              <li className="text-yellow-600">
                ... and {graph.cycles.length - 3} more
              </li>
            )}
          </ul>
        </div>
      )}

      {/* Info tooltip */}
      <div className="flex items-start gap-2 text-sm text-gray-600 bg-gray-50 p-3 rounded">
        <Info className="h-4 w-4 mt-0.5 flex-shrink-0" />
        <p>
          The causal graph shows task dependencies extracted from your farm
          prompt. Nodes represent actions/states, edges show causal
          relationships. The topological order determines optimal task
          execution sequence. Critical path nodes are highlighted in red.
        </p>
      </div>
    </div>
  );
};

export default CausalGraphVisualization;
