/**
 * Problem Model Viewer Component
 *
 * Displays the problem model generated by Model-First Reasoning
 * (arxiv 2512.14474) during the MODELING phase.
 *
 * Shows:
 * - Entities with types and relationships
 * - Variables with current values
 * - Actions with preconditions and effects
 * - Constraints with severity
 * - Goals with verification status
 */

import React, { useState } from 'react';
import {
  Box,
  FileCode,
  Settings,
  Target,
  AlertTriangle,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Layers,
  Zap,
  Lock,
  GitBranch,
} from 'lucide-react';

// Types matching the backend ProblemModel interfaces
interface ProblemEntity {
  id: string;
  name: string;
  type: string;
  properties: Record<string, unknown>;
  relationships: Array<{ targetId: string; type: string }>;
  description?: string;
}

interface ProblemVariable {
  id: string;
  name: string;
  type: string;
  domain?: unknown[];
  initialValue?: unknown;
  currentValue?: unknown;
  description?: string;
  tracked: boolean;
}

interface Condition {
  variable: string;
  operator: string;
  value: unknown;
  description?: string;
}

interface Effect {
  variable: string;
  operation: string;
  value: unknown;
}

interface ProblemAction {
  id: string;
  name: string;
  description: string;
  preconditions: Condition[];
  effects: Effect[];
  assignedAgent?: string;
  priority: number;
  status?: string;
}

interface ProblemConstraint {
  id: string;
  type: string;
  description: string;
  expression: string;
  enforced: boolean;
  severity: 'error' | 'warning' | 'info';
}

interface ProblemGoal {
  id: string;
  description: string;
  conditions: Condition[];
  priority: number;
  verified: boolean;
}

interface ProblemModel {
  id: string;
  farmId: string;
  entities: ProblemEntity[];
  variables: ProblemVariable[];
  actions: ProblemAction[];
  constraints: ProblemConstraint[];
  goals: ProblemGoal[];
  verified: boolean;
  verificationScore?: number;
}

interface ProblemModelViewerProps {
  model: ProblemModel;
  compact?: boolean;
}

const EntityTypeIcon: React.FC<{ type: string }> = ({ type }) => {
  const iconClass = 'h-4 w-4';
  switch (type) {
    case 'file':
      return <FileCode className={iconClass} />;
    case 'function':
    case 'class':
    case 'module':
      return <Box className={iconClass} />;
    case 'service':
    case 'api':
      return <Layers className={iconClass} />;
    case 'agent':
      return <Zap className={iconClass} />;
    default:
      return <Settings className={iconClass} />;
  }
};

const SeverityBadge: React.FC<{ severity: string }> = ({ severity }) => {
  const colors = {
    error: 'bg-red-100 text-red-800',
    warning: 'bg-yellow-100 text-yellow-800',
    info: 'bg-blue-100 text-blue-800',
  };

  return (
    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${colors[severity as keyof typeof colors] || colors.info}`}>
      {severity}
    </span>
  );
};

const ExpandableSection: React.FC<{
  title: string;
  count: number;
  icon: React.ReactNode;
  children: React.ReactNode;
  defaultExpanded?: boolean;
}> = ({ title, count, icon, children, defaultExpanded = false }) => {
  const [expanded, setExpanded] = useState(defaultExpanded);

  return (
    <div className="border rounded-lg overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between p-3 bg-gray-50 hover:bg-gray-100 transition-colors"
      >
        <div className="flex items-center space-x-2">
          {icon}
          <span className="font-medium">{title}</span>
          <span className="text-sm text-gray-500">({count})</span>
        </div>
        {expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
      </button>
      {expanded && <div className="p-3 border-t">{children}</div>}
    </div>
  );
};

export const ProblemModelViewer: React.FC<ProblemModelViewerProps> = ({ model, compact = false }) => {
  if (!model) {
    return (
      <div className="text-gray-500 text-center py-4">
        No problem model available
      </div>
    );
  }

  const verificationColor = model.verified ? 'text-green-600' : 'text-gray-400';
  const verificationIcon = model.verified ? (
    <CheckCircle className="h-5 w-5 text-green-500" />
  ) : (
    <AlertTriangle className="h-5 w-5 text-yellow-500" />
  );

  if (compact) {
    return (
      <div className="bg-white rounded-lg shadow p-4">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold text-lg">Problem Model</h3>
          <div className="flex items-center space-x-2">
            {verificationIcon}
            {model.verificationScore !== undefined && (
              <span className={verificationColor}>
                {(model.verificationScore * 100).toFixed(0)}%
              </span>
            )}
          </div>
        </div>
        {/* MOBILE FIX: Use responsive grid */}
        <div className="grid grid-cols-3 sm:grid-cols-5 gap-1.5 sm:gap-2 text-center text-xs sm:text-sm">
          <div className="bg-gray-50 dark:bg-gray-800 rounded p-1.5 sm:p-2">
            <div className="font-bold text-base sm:text-lg">{model.entities.length}</div>
            <div className="text-gray-600 dark:text-gray-400 truncate">Entities</div>
          </div>
          <div className="bg-gray-50 dark:bg-gray-800 rounded p-1.5 sm:p-2">
            <div className="font-bold text-base sm:text-lg">{model.variables.length}</div>
            <div className="text-gray-600 dark:text-gray-400 truncate">Variables</div>
          </div>
          <div className="bg-gray-50 dark:bg-gray-800 rounded p-1.5 sm:p-2">
            <div className="font-bold text-base sm:text-lg">{model.actions.length}</div>
            <div className="text-gray-600 dark:text-gray-400 truncate">Actions</div>
          </div>
          <div className="bg-gray-50 dark:bg-gray-800 rounded p-1.5 sm:p-2">
            <div className="font-bold text-base sm:text-lg">{model.constraints.length}</div>
            <div className="text-gray-600 dark:text-gray-400 truncate">Constraints</div>
          </div>
          <div className="bg-gray-50 dark:bg-gray-800 rounded p-1.5 sm:p-2">
            <div className="font-bold text-base sm:text-lg">{model.goals.length}</div>
            <div className="text-gray-600 dark:text-gray-400 truncate">Goals</div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow-md p-6 space-y-4">
      <div className="flex items-center justify-between border-b pb-4">
        <div>
          <h2 className="text-xl font-bold">Problem Model</h2>
          <p className="text-sm text-gray-600">Model-First Reasoning (arxiv 2512.14474)</p>
        </div>
        <div className="flex items-center space-x-3">
          {verificationIcon}
          <div className="text-right">
            <div className={`font-semibold ${verificationColor}`}>
              {model.verified ? 'Verified' : 'Unverified'}
            </div>
            {model.verificationScore !== undefined && (
              <div className="text-sm text-gray-500">
                Score: {(model.verificationScore * 100).toFixed(1)}%
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Entities */}
      <ExpandableSection
        title="Entities"
        count={model.entities.length}
        icon={<Layers className="h-5 w-5 text-blue-500" />}
        defaultExpanded={model.entities.length <= 5}
      >
        <div className="space-y-2">
          {model.entities.map((entity) => (
            <div key={entity.id} className="flex items-start space-x-3 p-2 bg-gray-50 rounded">
              <EntityTypeIcon type={entity.type} />
              <div className="flex-1 min-w-0">
                <div className="flex items-center space-x-2">
                  <span className="font-medium">{entity.name}</span>
                  <span className="text-xs text-gray-500 bg-gray-200 px-2 py-0.5 rounded">
                    {entity.type}
                  </span>
                </div>
                {entity.description && (
                  <p className="text-sm text-gray-600 truncate">{entity.description}</p>
                )}
                {entity.relationships.length > 0 && (
                  <div className="flex items-center space-x-1 mt-1">
                    <GitBranch className="h-3 w-3 text-gray-400" />
                    <span className="text-xs text-gray-500">
                      {entity.relationships.length} relationship(s)
                    </span>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </ExpandableSection>

      {/* Actions */}
      <ExpandableSection
        title="Actions"
        count={model.actions.length}
        icon={<Zap className="h-5 w-5 text-orange-500" />}
        defaultExpanded={model.actions.length <= 5}
      >
        <div className="space-y-3">
          {model.actions.map((action) => (
            <div key={action.id} className="border rounded p-3">
              <div className="flex items-center justify-between mb-2">
                <span className="font-medium">{action.name}</span>
                <div className="flex items-center space-x-2">
                  <span className="text-xs bg-blue-100 text-blue-800 px-2 py-0.5 rounded">
                    Priority: {action.priority}
                  </span>
                  {action.assignedAgent && (
                    <span className="text-xs bg-purple-100 text-purple-800 px-2 py-0.5 rounded">
                      {action.assignedAgent}
                    </span>
                  )}
                </div>
              </div>
              <p className="text-sm text-gray-600 mb-2">{action.description}</p>
              {action.preconditions.length > 0 && (
                <div className="text-xs">
                  <span className="font-medium text-gray-500">Preconditions:</span>
                  <ul className="ml-4 list-disc text-gray-600">
                    {action.preconditions.slice(0, 3).map((pc, i) => (
                      <li key={i}>{pc.variable} {pc.operator} {String(pc.value)}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ))}
        </div>
      </ExpandableSection>

      {/* Constraints */}
      <ExpandableSection
        title="Constraints"
        count={model.constraints.length}
        icon={<Lock className="h-5 w-5 text-red-500" />}
      >
        <div className="space-y-2">
          {model.constraints.map((constraint) => (
            <div key={constraint.id} className="flex items-start space-x-3 p-2 bg-gray-50 rounded">
              <div className="flex-1">
                <div className="flex items-center space-x-2 mb-1">
                  <span className="text-xs bg-gray-200 px-2 py-0.5 rounded">{constraint.type}</span>
                  <SeverityBadge severity={constraint.severity} />
                  {!constraint.enforced && (
                    <span className="text-xs text-gray-400">(not enforced)</span>
                  )}
                </div>
                <p className="text-sm">{constraint.description}</p>
              </div>
            </div>
          ))}
        </div>
      </ExpandableSection>

      {/* Goals */}
      <ExpandableSection
        title="Goals"
        count={model.goals.length}
        icon={<Target className="h-5 w-5 text-green-500" />}
        defaultExpanded
      >
        <div className="space-y-2">
          {model.goals.map((goal) => (
            <div key={goal.id} className="flex items-start space-x-3 p-2 bg-gray-50 rounded">
              {goal.verified ? (
                <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0" />
              ) : (
                <Target className="h-5 w-5 text-gray-400 flex-shrink-0" />
              )}
              <div className="flex-1">
                <div className="flex items-center space-x-2">
                  <span className={goal.verified ? 'text-green-700' : ''}>
                    {goal.description}
                  </span>
                  <span className="text-xs bg-gray-200 px-2 py-0.5 rounded">
                    Priority: {goal.priority}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </ExpandableSection>
    </div>
  );
};

export default ProblemModelViewer;
